### ISSUE TITLE
As a user, I expect the WRES to be able to handle when I ask for one NWM feature, but WRDS links that to multiple USGS gauges or NWS lids

### ISSUE THREAD

**Issue by epag** [NOAA-OWP/wres#114]
---

Author Name: **Hank** (Hank)
Original Redmine Issue: 116284, https://vlab.noaa.gov/redmine/issues/116284
Original Date: 2023-05-16
Original Assignee: Hank

---

The complete evaluation declaration will be provided in comment 1. Here is the exception:

```
2023-05-16T18:23:07.276+0000 ERROR Main Operation 'execute' completed unsuccessfully
wres.pipeline.InternalWresException: Could not complete project execution
	at wres.pipeline.Evaluator.evaluate(Evaluator.java:319)
	at wres.pipeline.Evaluator.evaluate(Evaluator.java:162)
	at wres.Functions.execute(Functions.java:209)
	at wres.Functions.call(Functions.java:135)
	at wres.Main.completeExecution(Main.java:233)
	at wres.Main.main(Main.java:135)
Caused by: wres.pipeline.WresProcessingException: Encountered an error while processing evaluation 'bx1WkRzRNe0u_lZXENdolZ8XVPQ': 
	at wres.pipeline.EvaluationUtilities.evaluate(EvaluationUtilities.java:283)
	at wres.pipeline.Evaluator.evaluate(Evaluator.java:294)
	... 5 common frames omitted
Caused by: wres.pipeline.WresProcessingException: Project failed to complete with the following error: 
	at wres.pipeline.EvaluationUtilities.evaluate(EvaluationUtilities.java:565)
	at wres.pipeline.EvaluationUtilities.evaluate(EvaluationUtilities.java:229)
	... 6 common frames omitted
Caused by: wres.io.ingesting.PreIngestException: Response from WRDS at https://nwcal-wrds.[host]/api/location/v3.0/metadata/nwm_feature_id/4492122,4489096,4491898,4495656,4494460,4495672,4495272,9888592,9889000,4482885,9890672,4491946,4489178,4488242,4492036,4495704,4491268,4489180,4494690,9890662,4482733,4482999,4483009,9517822,4491878,9888528/?identifiers=true did not include exactly 26 locations,  but had 32. By declaring a feature, WRES interprets it as an intent to use that feature in the evaluation. If the corresponding feature cannot be found or has no correlation from the featureService, WRES prefers to inform you that the declared evaluation including that feature cannot be started. Options to resolve include any of: investigate the URL above in a web browser, report to the geographic feature service team the service issue or the data issue (e.g. expected correlation), omit this feature from the declaration, include a complete feature correlation declaration, or contact the WRES team for help.
	at wres.io.geography.wrds.WrdsFeatureService.getBatchOfFeatures(WrdsFeatureService.java:625)
	at wres.io.geography.wrds.WrdsFeatureService.bulkLookup(WrdsFeatureService.java:232)
	at wres.io.geography.wrds.WrdsFeatureFinder.fillFeatures(WrdsFeatureFinder.java:580)
	at wres.io.geography.wrds.WrdsFeatureFinder.fillSingletonFeatures(WrdsFeatureFinder.java:247)
	at wres.io.geography.wrds.WrdsFeatureFinder.fillFeatures(WrdsFeatureFinder.java:140)
	at wres.pipeline.EvaluationUtilities.evaluate(EvaluationUtilities.java:363)
	... 7 common frames omitted

```

It includes a list of @feature@ tags, each one only specifying the @right@ (@predicted@) feature identifier.  Being NWM features, for some of them, WRDS will return more than one USGS gauge id.  This should be expected, but I'll double check the WRDS response as part of this investigation.  I'd like for the WRES to still be able to complete the evaluation, though how it handles the NWM features with multiple USGS gages is TBD.

I'm going to prepare some information, but whether we want to handle this in 6.14 is TBD. Still, I assign it to that target version for now.

Thanks,

Hank

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Hank** (Hank)
Original Date: 2023-05-16T18:49:09Z

---

Note that I am reporting this problem against 6.13. When I attempt this same declaration using the latest code in development, I encounter an NPE per #116282.

Here is the XML declaration:

```<code class="xml">
<?xml version='1.0' encoding='UTF-8'?>
<project name="RFC Training Example NWM Single-Valued">
  <inputs>
    <left label="USGS NWIS Streamflow Observations">
      <type>observations</type>
      <source interface="usgs_nwis">https://nwis.waterservices.usgs.gov/nwis/iv</source>
      <variable>00060</variable>
    </left>
    <right featureDimension="nwm_feature_id" label="WRDS NWM MRF Single Valued Streamflow Forecasts">
      <type>single valued forecasts</type>
      <source interface="wrds_nwm">https://[production WRDS]/api/nwm2.1/v2.0/ops/medium_range</source>
      <variable>streamflow</variable>
      <urlParameter>
        <name>unassimilated</name>
        <value>true</value>
      </urlParameter>
    </right>
  </inputs>
  <pair label="RFC Training Pair Declaration">
    <unit>ft3/s</unit>
    <featureService>
      <baseUrl>https:[production WRDS]/api/location/v3.0/metadata</baseUrl>
<!--      <group pool="false">
        <type>rfc</type>
        <value>MARFC</value>
      </group>-->
    </featureService>

<feature right="4482733"/>
<feature right="4482885"/>
<feature right="4482999"/>
<feature right="4483009"/>
<feature right="4488242"/>
<feature right="4489096"/>
<feature right="4489178"/>
<feature right="4489180"/>
<feature right="4491268"/>
<feature right="4491878"/>
<feature right="4491898"/>
<feature right="4491946"/>
<feature right="4492036"/>
<feature right="4492122"/>
<feature right="4494460"/>
<feature right="4494690"/>
<feature right="4495272"/>
<feature right="4495656"/>
<feature right="4495672"/>
<feature right="4495704"/>
<feature right="9517822"/>
<feature right="9888528"/>
<feature right="9888592"/>
<feature right="9889000"/>
<feature right="9890662"/>
<feature right="9890672"/>

    <leadHours minimum="0" maximum="240"/>
    <dates earliest="2023-05-05T00:00:00Z" latest="2023-05-15T12:26:38Z"/>
    <issuedDates earliest="2023-05-05T00:00:00Z" latest="2023-05-15T12:26:38Z"/>
    <leadTimesPoolingWindow>
      <period>1</period>
      <frequency>1</frequency>
      <unit>hours</unit>
    </leadTimesPoolingWindow>
  </pair>
  <metrics>
    <thresholds>
      <type>value</type>
      <applyTo>left</applyTo>
      <source format="wrds" ratingProvider="NRLDB" parameterToMeasure="flow" featureNameFrom="right">https://nwcal-[production WRDS]/api/location/v3.0/nws_threshold/</source>
      <operator>greater than or equal to</operator>
    </thresholds>
    <metric>
      <name>pearson correlation coefficient</name>
    </metric>
    <metric>
      <name>sample size</name>
    </metric>
    <metric>
      <name>mean error</name>
    </metric>
  </metrics>
  <outputs durationFormat="hours">
    <destination type="graphic">
      <outputType>lead threshold</outputType>
    </destination>
    <destination type="netcdf2"/>
    <destination type="csv2"/>
  </outputs>
</project>
</code>
```

Hank

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Hank** (Hank)
Original Date: 2023-05-16T18:50:19Z

---

Adding the exception to the Description.

Hank

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Hank** (Hank)
Original Date: 2023-05-16T18:52:36Z

---

Here is the WRDS response for the request noted in the description:

```<code class="json">
{
    "_metrics": {
        "location_count": 32,
        "model_tracing_api_call": 0.010681867599487305,
        "total_request_time": 0.8429915904998779
    },
    "_warnings": [],
    "_documentation": {
        "swagger URL": "http://[production WRDS]/docs/location/v3.0/swagger/"
    },
    "deployment": {
        "api_url": "https://[production WRDS]/api/location/v3.0/metadata/nwm_feature_id/4492122,4489096,4491898,4495656,4494460,4495672,4495272,9888592,9889000,4482885,9890672,4491946,4489178,4488242,4492036,4495704,4491268,4489180,4494690,9890662,4482733,4482999,4483009,9517822,4491878,9888528/?identifiers=true",
        "stack": "prod",
        "version": "v3.5.6",
        "api_caller": "None"
    },
    "Non-urgent_issue_reporting_link": "https://vlab.noaa.gov/redmine/projects/wrds-user-support/issues/new?issue[category_id]=2830",
    "data_sources": {
        "metadata_sources": [
            "NWS data: NRLDB - Last updated: 2023-05-10 12:55:18 UTC",
            "USGS data: USGS NWIS - Last updated: 2023-05-10 12:10:55 UTC"
        ],
        "crosswalk_datasets": {
            "location_nwm_crosswalk_dataset": {
                "location_nwm_crosswalk_dataset_id": "1.2",
                "name": "Location NWM Crosswalk v1.2",
                "description": "Created 20220831.  Source:\n1) NWM Routelink File v2.2-corrected\n2) NHDPlus v2.1+\n3) GID"
            },
            "nws_usgs_crosswalk_dataset": {
                "nws_usgs_crosswalk_dataset_id": "2.0",
                "name": "NWS Station to USGS Gages 2.0",
                "description": "Created 2021-12-10.  Authoritative 2.0 dataset mapping NWS Stations to USGS Gages.  Source 1) AHPS CMS Report  2) HADS dataset  3) GID"
            }
        }
    },
    "locations": [
        {
            "identifiers": {
                "nws_lid": "SEKV2",
                "usgs_site_code": null,
                "nwm_feature_id": "9889000",
                "goes_id": null,
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [],
            "downstream_nwm_features": [
                "9889026"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "WETN4",
                "usgs_site_code": "01402540",
                "nwm_feature_id": "9517822",
                "goes_id": "DDC43374",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "9514118",
                "9513872"
            ],
            "downstream_nwm_features": [
                "9513466"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "CHLP1",
                "usgs_site_code": "01464720",
                "nwm_feature_id": "4482733",
                "goes_id": "DE446656",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4482707",
                "4482709"
            ],
            "downstream_nwm_features": [
                "4482757"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "RUSP1",
                "usgs_site_code": "01464750",
                "nwm_feature_id": "4482999",
                "goes_id": "DD2296C8",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4482821",
                "4482997"
            ],
            "downstream_nwm_features": [
                "4482843"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "NSHP1",
                "usgs_site_code": "01464907",
                "nwm_feature_id": "4482885",
                "goes_id": "16D0C4AC",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4482917",
                "4482891"
            ],
            "downstream_nwm_features": [
                "4482883"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "PEPP1",
                "usgs_site_code": "01465200",
                "nwm_feature_id": "4483009",
                "goes_id": "163AE698",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4483007",
                "4483013"
            ],
            "downstream_nwm_features": [
                "4482849"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "POQP1",
                "usgs_site_code": "01465798",
                "nwm_feature_id": "4488242",
                "goes_id": "17EB83DC",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4488228",
                "4487994"
            ],
            "downstream_nwm_features": [
                "4488278"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "VNCN4",
                "usgs_site_code": "01465850",
                "nwm_feature_id": "4492122",
                "goes_id": "DD4F979C",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4491956",
                "4490920"
            ],
            "downstream_nwm_features": [
                "4490780"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "MEDN4",
                "usgs_site_code": "01465880",
                "nwm_feature_id": "4491268",
                "goes_id": "DDBB90B2",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4491274",
                "4491284"
            ],
            "downstream_nwm_features": [
                "4491160"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "MCDN4",
                "usgs_site_code": "01466500",
                "nwm_feature_id": "4492036",
                "goes_id": "DD072368",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [],
            "downstream_nwm_features": [
                "4499256"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "NLBN4",
                "usgs_site_code": "01466900",
                "nwm_feature_id": "4491946",
                "goes_id": "DDBB83C4",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4490826",
                "4490838"
            ],
            "downstream_nwm_features": [
                "4490662"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "PEBN4",
                "usgs_site_code": "01467000",
                "nwm_feature_id": "4491898",
                "goes_id": "1761B0AC",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4490758",
                "4490660"
            ],
            "downstream_nwm_features": [
                "4490536"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "IWPN4",
                "usgs_site_code": "01467005",
                "nwm_feature_id": "4491878",
                "goes_id": "DD078390",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4490510",
                "4490512"
            ],
            "downstream_nwm_features": [
                "4490494"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "PLLP1",
                "usgs_site_code": "01467048",
                "nwm_feature_id": "4489178",
                "goes_id": "DE2865F8",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4489016",
                "4489018"
            ],
            "downstream_nwm_features": [
                "4489040"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "CHRN4",
                "usgs_site_code": "01467081",
                "nwm_feature_id": "4495672",
                "goes_id": "DD0755F8",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4491276"
            ],
            "downstream_nwm_features": [
                "4494558"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "TACP1",
                "usgs_site_code": "01467086",
                "nwm_feature_id": "4489180",
                "goes_id": "DDA7253E",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4489026",
                "4489028"
            ],
            "downstream_nwm_features": [
                "4489034"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "FCRP1",
                "usgs_site_code": "01467087",
                "nwm_feature_id": "4489096",
                "goes_id": "DE28860A",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4489034",
                "4489036"
            ],
            "downstream_nwm_features": [
                "4489206"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "HDDN4",
                "usgs_site_code": "01467150",
                "nwm_feature_id": "4494690",
                "goes_id": "17DFB50C",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4495892"
            ],
            "downstream_nwm_features": [
                "4494670"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "PITN4",
                "usgs_site_code": "01475001",
                "nwm_feature_id": "4495272",
                "goes_id": "DE236650",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4496396"
            ],
            "downstream_nwm_features": [
                "4496384"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "COBP1",
                "usgs_site_code": "01475530",
                "nwm_feature_id": "4495656",
                "goes_id": "17EC148A",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4489136"
            ],
            "downstream_nwm_features": [
                "4495680"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "NTSP1",
                "usgs_site_code": "01475850",
                "nwm_feature_id": "4494460",
                "goes_id": "162A9944",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4494434",
                "4494436"
            ],
            "downstream_nwm_features": [
                "4494476"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "RIDP1",
                "usgs_site_code": "01476480",
                "nwm_feature_id": "4495704",
                "goes_id": "DD0866F0",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4494626",
                "4494628"
            ],
            "downstream_nwm_features": [
                "4495710"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "BKNV2",
                "usgs_site_code": "0167862550",
                "nwm_feature_id": "9888528",
                "goes_id": "DDE8E56E",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "9888396"
            ],
            "downstream_nwm_features": [
                "9888530"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "NMCV2",
                "usgs_site_code": "0167892964",
                "nwm_feature_id": "9888592",
                "goes_id": "172B94CE",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "9888594"
            ],
            "downstream_nwm_features": [
                "9888576"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "THAV2",
                "usgs_site_code": "0204291317",
                "nwm_feature_id": "9890662",
                "goes_id": "DDE6C7EA",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "9890666",
                "9891546"
            ],
            "downstream_nwm_features": [
                "9891272"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "LONV2",
                "usgs_site_code": "0204293125",
                "nwm_feature_id": "9890672",
                "goes_id": "DDE8D0F4",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "9890684",
                "9890676"
            ],
            "downstream_nwm_features": [
                "9891270"
            ]
        },
        {
            "identifiers": {
                "nws_lid": "LTCV2",
                "usgs_site_code": "0204295505",
                "nwm_feature_id": "9889000",
                "goes_id": "172B01AC",
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [],
            "downstream_nwm_features": [
                "9889026"
            ]
        },
        {
            "identifiers": {
                "nws_lid": null,
                "usgs_site_code": "01476500",
                "nwm_feature_id": "4495704",
                "goes_id": null,
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4494626",
                "4494628"
            ],
            "downstream_nwm_features": [
                "4495710"
            ]
        },
        {
            "identifiers": {
                "nws_lid": null,
                "usgs_site_code": "01465882",
                "nwm_feature_id": "4491268",
                "goes_id": null,
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4491274",
                "4491284"
            ],
            "downstream_nwm_features": [
                "4491160"
            ]
        },
        {
            "identifiers": {
                "nws_lid": null,
                "usgs_site_code": "01467045",
                "nwm_feature_id": "4489178",
                "goes_id": null,
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4489016",
                "4489018"
            ],
            "downstream_nwm_features": [
                "4489040"
            ]
        },
        {
            "identifiers": {
                "nws_lid": null,
                "usgs_site_code": "01467089",
                "nwm_feature_id": "4489096",
                "goes_id": null,
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4489034",
                "4489036"
            ],
            "downstream_nwm_features": [
                "4489206"
            ]
        },
        {
            "identifiers": {
                "nws_lid": null,
                "usgs_site_code": "01467004",
                "nwm_feature_id": "4491878",
                "goes_id": null,
                "env_can_gage_id": null
            },
            "upstream_nwm_features": [
                "4490510",
                "4490512"
            ],
            "downstream_nwm_features": [
                "4490494"
            ]
        }
    ]
}
</code>
```

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Hank** (Hank)
Original Date: 2023-05-16T18:57:54Z

---

The problematic features:

4489096
4489178
4491268
4491878
4495704
9889000

-I may have overlooked others.- EDIT: I updated the above to the full list.

Hank

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2023-05-16T19:03:32Z

---

I doubt v6.14. There is going to be a *lot* in v6.14 as-is.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Hank** (Hank)
Original Date: 2023-05-16T19:12:37Z

---

Yeah, I was guessing as much.

Hank

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2024-06-28T12:02:55Z

---

On the fence about migrating WRDS stuff. It does affect the core code, even if WRDS is not available to external users. Increasingly of the opinion that it will be hard to separate out development tickets that relate to generally available and NWS-centric services and we should restrict vlab to COWRES infrastructure and service maintenance tickets, but put all dev on github.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Hank** (Hank)
Original Date: 2024-06-28T12:14:48Z

---

James wrote:
> Increasingly of the opinion that it will be hard to separate out development tickets that relate to generally available and NWS-centric services and we should restrict vlab to COWRES infrastructure and service maintenance tickets, but put all dev on github.

I agree, for what its worth.

Hank
