### ISSUE TITLE
As a user, I don't want NPE on netcdf output for NWM vs USGS evaluation

### ISSUE THREAD

**Issue by epag** [NOAA-OWP/wres#214]
---

Author Name: **Jesse** (Jesse)
Original Redmine Issue: 65767, https://vlab.noaa.gov/redmine/issues/65767
Original Date: 2019-07-08

---

Given evaluation of NWM medium range vs USGS obs from NWIS
When netcdf output is selected
Then it should not NPE

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Jesse** (Jesse)
Original Date: 2019-07-08T21:20:30Z

---

wres8 db run at 2019-07-08 20:31:55.988
```
wres.control.WresProcessingException: Project failed to complete with the following error:
         at wres.control.ProcessorHelper.processProjectConfig(ProcessorHelper.java:237)
         at wres.control.Control.accept(Control.java:246)
         at wres.control.Control.apply(Control.java:133)
         at wres.control.Control.apply(Control.java:49)
         at wres.MainFunctions.call(MainFunctions.java:96)
         at wres.Main.main(Main.java:94)
 Caused by: java.util.concurrent.CompletionException: wres.control.WresProcessingException: While processing feature CLAI2
         at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
         at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
         at java.base/java.lang.Thread.run(Thread.java:834)
 Caused by: wres.control.WresProcessingException: While processing feature CLAI2
         at wres.control.FeatureProcessor.get(FeatureProcessor.java:255)
         at wres.control.FeatureProcessor.get(FeatureProcessor.java:43)
         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
         ... 3 more
 Caused by: java.util.concurrent.CompletionException: java.lang.NullPointerException
         at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
         at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
         at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
         at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
         at java.base/java.util.concurrent.ThreadPoolExecutor$CallerRunsPolicy.rejectedExecution(ThreadPoolExecutor.java:2027)
         at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
         at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
         at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
         at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:638)
         at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
         at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
         at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
         at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
         at java.base/java.util.concurrent.ThreadPoolExecutor$CallerRunsPolicy.rejectedExecution(ThreadPoolExecutor.java:2027)
         at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
         at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
         at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
         at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:638)
         at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
         ... 3 more
 Caused by: java.lang.NullPointerException
         at wres.io.writing.netcdf.MetricVariable.<init>(MetricVariable.java:69)
         at wres.io.writing.netcdf.MetricVariable.getAll(MetricVariable.java:40)
         at wres.io.writing.netcdf.NetcdfOutputWriter.accept(NetcdfOutputWriter.java:190)
         at wres.io.writing.SharedStatisticsWriters.accept(SharedStatisticsWriters.java:130)
         at wres.io.writing.SharedStatisticsWriters.accept(SharedStatisticsWriters.java:26)
         at wres.control.ProduceOutputsFromStatistics.processDoubleScoreOutputs(ProduceOutputsFromStatistics.java:683)
         at wres.control.ProduceOutputsFromStatistics.accept(ProduceOutputsFromStatistics.java:273)
         at wres.control.FeatureProcessor.lambda$get$1(FeatureProcessor.java:195)
         at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
         ... 20 more

```

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Jesse** (Jesse)
Original Date: 2019-07-08T21:21:43Z

---

Same/similar project as #65503 which gave IOOBE in 1.9, but now in 1.10 gives NPE on netcdf, but runs successfully to completion with only png,pairs,csv.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Jesse** (Jesse)
Original Date: 2019-07-08T22:19:51Z

---

From 2019-07-05
```
2019-07-05T20:56:37.618+0000 1461 [main] INFO wres.Main - WRES version 20190626-e953480
2019-07-05T20:56:37.639+0000 1461 [main] INFO wres.Main - Processors: 4; Max Memory: 2310MiB; Free Memory: 2290MiB; Total Memory: 2310MiB; awt.toolkit: sun.awt.X11.XToolkit; file.encoding: ANSI_X3.4-1968; java.awt.graphicsenv: sun.awt.X11GraphicsEnvironment; java.class.version: 55.0; java.home: /usr/lib/jvm/java-11-openjdk-11.0.3.7-0.el7_6.x86_64; java.io.tmpdir: /mnt/wres_share/evaluations/wres_job_-8768177009002436966_3709503995765740077; java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib; java.runtime.name: OpenJDK Runtime Environment; java.runtime.version: 11.0.3+7-LTS; java.util.logging.config.class: wres.system.logging.JavaUtilLoggingRedirector; java.version: 11.0.3; java.version.date: 2019-04-16; java.vm.compressedOopsMode: Zero based; java.vm.info: mixed mode, sharing; java.vm.name: OpenJDK 64-Bit Server VM; java.vm.vendor: Oracle Corporation; java.vm.version: 11.0.3+7-LTS; jdk.debug: release; os.arch: amd64; os.name: Linux; os.version: 3.10.0-957.21.2.el7.x86_64; user.dir: /opt/wres-worker-20190510-c665196; user.home: /home/wres_docker; user.language: en; user.name: wres_docker; user.timezone: UTC; wres.databaseName: wres8; wres.url: nwcal-rdb.[host]; wres.username: wres_user8
2019-07-05T20:56:40.822+0000 1461 [main] INFO wres.system.SystemSettings - wres.system.SystemSettings@748d2277[databaseConfiguration=wres.system.DatabaseSettings@2f897dab[url=nwcal-rdb.[host],username=wres_user8,port=5432,databaseName=wres8,databaseType=postgresql,certificateFileToTrust=classpath:nwcal_ca_expires_2020-06.pem,maxPoolSize=8,maxIdleTime=80,connectionProperties={sslfactory=wres.system.PgSSLSocketFactory, ssl=true, sslfactoryarg=classpath:nwcal_ca_expires_2020-06.pem},useSSL=true,validateSSL=true,queryTimeout=18000],maximumThreadCount=7,poolObjectLifespan=30000,fetchSize=50000,maximumCopies=10000,defaultChartWidth=800,defaultChartHeight=600,netcdfCachePeriod=90,minimumCachedNetcdf=100,maximumCachedNetcdf=200,hardNetcdfCacheLimit=0,netcdfStorePath=systests/data/,maximumArchiveThreads=5,maximumWebClientThreads=3,dataDirectory=/opt/wres-worker-20190510-c665196]
2019-07-05T20:56:40.833+0000 1461 [main] INFO wres.Main - Process: 1461
2019-07-05T20:56:40.837+0000 1461 [main] INFO wres.Main - Beginning operation: 'execute' at 2019-07-05T20:56:40.834323Z...
2019-07-05T20:56:41.401+0000 1461 [main] INFO wres.config.ProjectConfigPlus - Unmarshalled project configuration from command line argument
2019-07-05T20:56:41.402+0000 1461 [main] INFO wres.control.Control - Successfully unmarshalled project configuration from command line argument, validating further...
2019-07-05T20:56:41.422+0000 1461 [main] INFO wres.control.Control - Successfully validated project configuration from command line argument. Beginning execution...
2019-07-05T20:56:41.470+0000 1461 [main] INFO wres.io.reading.SourceLoader - Parsing files. Only 8 files may be parsed at once.
2019-07-05T20:56:45.073+0000 1461 [main] INFO wres.io.Operations - Loading preliminary metadata...
2019-07-05T20:56:45.186+0000 1461 [main] WARN wres.io.project.Project - Could not determine valid time scale information for one or more RIGHT sources. Assuming that the desired time scale is consistent with the time scales of the sources for which information is missing.
2019-07-05T20:56:45.193+0000 1461 [main] WARN wres.io.project.Project - The left sources do not have a consistent time step. Found 3 different time steps across all left sources, namely: [PT5M, PT15M, PT30M].
2019-07-05T20:56:47.932+0000 1461 [main] INFO wres.io.Operations - Preliminary metadata loading is complete.
2019-07-05T20:57:03.961+0000 1461 [main] ERROR wres.control.Control - Could not complete project execution due to:
wres.control.WresProcessingException: Project failed to complete with the following error: 
	at wres.control.ProcessorHelper.processProjectConfig(ProcessorHelper.java:237)
	at wres.control.Control.accept(Control.java:246)
	at wres.control.Control.apply(Control.java:133)
	at wres.control.Control.apply(Control.java:49)
	at wres.MainFunctions.call(MainFunctions.java:96)
	at wres.Main.main(Main.java:94)
Caused by: java.util.concurrent.CompletionException: wres.control.WresProcessingException: While processing feature CLAI2
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: wres.control.WresProcessingException: While processing feature CLAI2
	at wres.control.FeatureProcessor.get(FeatureProcessor.java:255)
	at wres.control.FeatureProcessor.get(FeatureProcessor.java:43)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 3 common frames omitted
Caused by: java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor$CallerRunsPolicy.rejectedExecution(ThreadPoolExecutor.java:2027)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:638)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor$CallerRunsPolicy.rejectedExecution(ThreadPoolExecutor.java:2027)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:638)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
	... 3 common frames omitted
Caused by: java.lang.NullPointerException: null
	at wres.io.writing.netcdf.MetricVariable.<init>(MetricVariable.java:69)
	at wres.io.writing.netcdf.MetricVariable.getAll(MetricVariable.java:40)
	at wres.io.writing.netcdf.NetcdfOutputWriter.accept(NetcdfOutputWriter.java:190)
	at wres.io.writing.SharedStatisticsWriters.accept(SharedStatisticsWriters.java:130)
	at wres.io.writing.SharedStatisticsWriters.accept(SharedStatisticsWriters.java:26)
	at wres.control.ProduceOutputsFromStatistics.processDoubleScoreOutputs(ProduceOutputsFromStatistics.java:683)
	at wres.control.ProduceOutputsFromStatistics.accept(ProduceOutputsFromStatistics.java:273)
	at wres.control.FeatureProcessor.lambda$get$1(FeatureProcessor.java:195)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 20 common frames omitted
2019-07-05T20:57:10.364+0000 1461 [main] ERROR wres.Main - Operation 'execute' completed unsuccessfully
wres.control.InternalWresException: Could not complete project execution
	at wres.control.Control.accept(Control.java:258)
	at wres.control.Control.apply(Control.java:133)
	at wres.control.Control.apply(Control.java:49)
	at wres.MainFunctions.call(MainFunctions.java:96)
	at wres.Main.main(Main.java:94)
Caused by: wres.control.WresProcessingException: Project failed to complete with the following error: 
	at wres.control.ProcessorHelper.processProjectConfig(ProcessorHelper.java:237)
	at wres.control.Control.accept(Control.java:246)
	... 4 common frames omitted
Caused by: java.util.concurrent.CompletionException: wres.control.WresProcessingException: While processing feature CLAI2
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: wres.control.WresProcessingException: While processing feature CLAI2
	at wres.control.FeatureProcessor.get(FeatureProcessor.java:255)
	at wres.control.FeatureProcessor.get(FeatureProcessor.java:43)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 3 common frames omitted
Caused by: java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor$CallerRunsPolicy.rejectedExecution(ThreadPoolExecutor.java:2027)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:638)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor$CallerRunsPolicy.rejectedExecution(ThreadPoolExecutor.java:2027)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:638)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
	... 3 common frames omitted
Caused by: java.lang.NullPointerException: null
	at wres.io.writing.netcdf.MetricVariable.<init>(MetricVariable.java:69)
	at wres.io.writing.netcdf.MetricVariable.getAll(MetricVariable.java:40)
	at wres.io.writing.netcdf.NetcdfOutputWriter.accept(NetcdfOutputWriter.java:190)
	at wres.io.writing.SharedStatisticsWriters.accept(SharedStatisticsWriters.java:130)
	at wres.io.writing.SharedStatisticsWriters.accept(SharedStatisticsWriters.java:26)
	at wres.control.ProduceOutputsFromStatistics.processDoubleScoreOutputs(ProduceOutputsFromStatistics.java:683)
	at wres.control.ProduceOutputsFromStatistics.accept(ProduceOutputsFromStatistics.java:273)
	at wres.control.FeatureProcessor.lambda$get$1(FeatureProcessor.java:195)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 20 common frames omitted
2019-07-05T20:57:10.471+0000  [Thread-0] INFO wres.MainFunctions - 
2019-07-05T20:57:10.473+0000  [Thread-0] INFO wres.MainFunctions - Forcefully shutting down the application (you may see some errors)...
2019-07-05T20:57:10.473+0000  [Thread-0] INFO wres.io.Operations - Forcefully shutting down the IO module...
2019-07-05T20:57:10.481+0000  [Thread-0] INFO wres.io.Operations - IO module was forcefully shut down. Abandoned around 0 executor tasks and around 0 database tasks.
2019-07-05T20:57:10.485+0000  [Thread-0] INFO wres.Main - The function 'execute' took 29.0s

```

**Comment by james-d-brown** [comment]
Hmmm, unable to read that old nwm data, seemingly no matter the declaration used. This was from a time before `interface` existed, so I am assuming it is nwm medium-range ensemble data, as alluded to in the discussion/naming. All data is skipped.

**Comment by james-d-brown** [comment]
No matter, the legacy netcdf is known to be broken, so this ticket can be marked will not fix (insofar as it needs to be fixed). However, I did discover a separate bug while attempting to run this one, for which I will open a separate ticket.
