### ISSUE TITLE
As a user, I want the WRES to tell me that data could not be retrieved because of the issued times pooling window configuration

### ISSUE THREAD

**Issue by epag** [NOAA-OWP/wres#233]
---

Author Name: **Chris** (Chris)
Original Redmine Issue: 81519, https://vlab.noaa.gov/redmine/issues/81519
Original Date: 2020-08-05

---

I was helping Peggy troubleshoot a project earlier today:

```<code class="xml">
<?xml version='1.0' encoding='UTF-8'?>
<project name="test_mv_0712_TN_and_DeepSouth">
  <inputs>
    <left label="USGS NWIS Streamflow Obs">
      <type>observations</type>
      <source>https://nwis.waterservices.usgs.gov/nwis/iv</source>
      <variable>00060</variable>
    </left>
    <right label="WRDS NWM API SRF">
      <type>single valued forecasts</type>
      <source interface="wrds_nwm">http://nwcal-wrds.[host]/api/v1/nwm/ops/short_range/</source>
      <variable>streamflow</variable>
    </right>
  </inputs>
  <pair label="SRF Pairs">
    <unit>ft3/s</unit>
    <feature rfc="serfc"/>
    <feature rfc="lmrfc"/>
    <feature rfc="ohrfc"/>
    <leadHours minimum="0" maximum="18"/>
    <dates earliest="2020-07-10T00:06:00Z" latest="2020-07-14T00:00:00Z"/>
    <issuedDates earliest="2020-07-10T00:06:00Z" latest="2020-07-14T00:00:00Z"/>
    <issuedDatesPoolingWindow>
      <period>0</period>
      <frequency>1</frequency>
      <unit>hours</unit>
    </issuedDatesPoolingWindow>
  </pair>
  <metrics>
    <thresholds>
      <type>value</type>
      <applyTo>left</applyTo>
      <source format="csv" missingValue="-999.0" featureType="nwsId">/home/ISED/wres/thresholds_from_peggy.csv</source>
      <operator>greater than or equal to</operator>
    </thresholds>
    <metric>
      <name>equitable threat score</name>
    </metric>
  </metrics>
  <outputs durationFormat="hours">
    <destination type="netcdf">
      <outputType>default</outputType>
    </destination>
  </outputs>
</project>
</code>
```

It all looked fine and ran, but it was never able to form pairs. After some experimentation, it turns out that changing the issue pooling to collect over a period of an hour rather than a frequency of an hour made everything work to completion.

If this creates a condition where nothing would ever be retrieved, I'd like to be told. This sort of configuration works with lead times pooling, but apparently not for issued time pooling.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2020-08-05T20:21:31Z

---

Hmmm, sounds more like a bug than a validation issue(?).

If there are forecasts issued on a PT1H timestep, counting forwards from (and not including) @2020-07-10T00:06:00Z@ and stopping at (and including) @2020-07-14T00:00:00Z@, then this should produce pairs, other factors being equal (I don't immediately see any unequal factors).

Would need to turn on debug logging for @wres.io.retrieval@ to see the retrieval scripts, but the pooling windows should be half-open intervals, so even "zero-width" intervals should capture an instant.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2020-08-05T20:22:56Z

---

And if it isn't a bug, then I'm not sure there's much we can do. We can validate declaration, but the declaration looks fine. Determining whether pairs exist cannot be done more simply/cheaply than doing the retrieval and attempting to form pairs.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2020-08-05T20:42:35Z

---

By way of example, I just adapted system test scenario003 to say this, which is directly analogous, I think:

```<code class="xml">
    <pair label="Pairs by location and lead time"> <!-- required for unit -->
        <unit>CMS</unit>
        <feature left="DRRC2HSF" right="DRRC2HSF" />
        <leadHours minimum="1" maximum="24" />
        <issuedDates earliest="1985-06-01T11:00:00Z" latest="1985-06-30T12:00:00Z"/>
        <issuedDatesPoolingWindow>
            <period>0</period>
            <frequency>1</frequency>
            <unit>hours</unit>
        </issuedDatesPoolingWindow>
    </pair>
</code>
```

And that produced expected output. So I guess there must be something peculiar about your dataset...

( All that to say, it's possible to form pools on issued datetime instants, nothing more. )

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Chris** (Chris)
Original Date: 2020-08-05T20:45:51Z

---

Yeah, I was pretty sure that was the case, which is why this situation was confusing.  Modifying scenario700 might yield a different result if there's some hidden gremlin somewhere.

If there's nothing we can do, that sort of sucks, but what can you do. If it's something obvious that can be caught in code, like <code class="sql">...AND TS.initialization_date > '2020-07-10T00:06:00Z' AND TS.initialization_date <= '2020-07-10T00:06:00Z'</code> it would be neat to see something or get that situation addressed.

It's marked low priority for a reason; I lost a chunk of time today trying to figure out what was going on, but it's not the end of the world or anything. 

As far as messaging is concerned, this is all that we're currently getting:

```
2020-08-05T16:18:11.989+0000 WARN FeatureReporter [1865/1866] Completed feature 'SSRS1', but no statistics were produced. This probably occurred because no pools contained valid pairs.
2020-08-05T16:18:12.017+0000 WARN FeatureReporter [1866/1866] Completed feature 'BORT1', but no statistics were produced. This probably occurred because no pools contained valid pairs.
2020-08-05T16:18:12.114+0000 ERROR Control Could not complete project execution due to:
wres.control.WresProcessingException: No features were successfully evaluated.
	at wres.control.FeatureReporter.report(FeatureReporter.java:165)
	at wres.control.ProcessorHelper.processProjectConfig(ProcessorHelper.java:263)
	at wres.control.Control.accept(Control.java:287)
	at wres.control.Control.apply(Control.java:168)
	at wres.MainFunctions.execute(MainFunctions.java:139)
	at wres.MainFunctions.call(MainFunctions.java:105)
	at wres.Main.main(Main.java:100)
2020-08-05T16:18:12.159+0000 ERROR Main Operation 'execute' completed unsuccessfully
wres.control.InternalWresException: Could not complete project execution
	at wres.control.Control.accept(Control.java:303)
	at wres.control.Control.apply(Control.java:168)
	at wres.MainFunctions.execute(MainFunctions.java:139)
	at wres.MainFunctions.call(MainFunctions.java:105)
	at wres.Main.main(Main.java:100)
Caused by: wres.control.WresProcessingException: No features were successfully evaluated.
	at wres.control.FeatureReporter.report(FeatureReporter.java:165)
	at wres.control.ProcessorHelper.processProjectConfig(ProcessorHelper.java:263)
	at wres.control.Control.accept(Control.java:287)
	... 4 common frames omitted

```

It's definitely not wrong, it's just not helpful.

If this is too tall of an order, this can be rejected or closed.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2020-08-05T20:49:43Z

---

I see, thanks for clarifying.

Assuming there isn't a bug (and I think it's worth double-checking this, because it looks like your declaration should succeed, assuming there are observations available), then I cannot think of any clever way to make the failure happen sooner or to clarify the nature of the failure. But I think the latter may be easier than the former. To put it differently, if there were a clever way to fail quicker, I think that thing would be the new pairing. But I think you're probably looking more for better messaging, i.e., what went wrong, what should you try next?

Perhaps we can improve the exception message somehow, but I'm not exactly sure how if no pairs are found. Certainly open to ideas on that. Maybe a suggestion about increasing the size of the buckets?

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Chris** (Chris)
Original Date: 2020-08-05T21:01:27Z

---

I think you have the right of it; it would have saved me a bunch of time if it was somehow able to tell what _might_ have went wrong and what to try next instead of just trying random theories.

While I think it would have been neat to predict this would have failed for some reason, *that* sounds like it would be pretty difficult. I'd be fine with just a message like:

```
2020-08-05T16:18:12.017+0000 WARN FeatureReporter [1866/1866] Completed feature 'BORT1', but no pools could be loaded due to something in your issued times pooling window. Might want to check that one out, genius.

```

The suggestion for the bucket message is already a better solution than any I've come up with. I'd say it would be neat to see the dimensions for the pools and what affected them, but that'd be information overload.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2020-08-05T21:07:25Z

---

OK, sounds good. When someone gets around to this, I'd suggest that, as a minimum, we add something like this:

> [...] This probably occurred because no pools contained valid pairs. To increase the chance that a pool contains valid pairs, you may increase the size of each pool. Your declaration included [issued datetime pooling windows and lead duration pooling windows]. You could try to make [either or both of] these types of pools larger.

That type of message wouldn't be too hard at all. It wouldn't always be correct, but it would be a hint that would help in many cases and it would only need to see the declaration. I think it would be tough to append the actual pools, like you say, because you could have more than a handful of them for each feature. I think that's a minimal thing we could do. There may be other things, but those other things probably quickly approach a lot of complexity.
