### ISSUE TITLE
As a user, I want to evaluate streamflow data from the NWIS daily values service

### ISSUE THREAD

**Issue by epag** [NOAA-OWP/wres#258]
---

Author Name: **James** (James)
Original Redmine Issue: 91342, https://vlab.noaa.gov/redmine/issues/91342
Original Date: 2021-04-27

---

Given an evaluation that requires streamflow data from the NWIS Daily Values web service
When I declare that evaluation in WRES
Then I should be able to choose the NWIS Daily Values web service and have that evaluation succeed

( So that I can complete HEFS baseline validations without downloading and reformatting the data myself, off to the side. )

---

Redmine related issue(s): [96660](https://vlab.noaa.gov/redmine/issues/96660), [99415](https://vlab.noaa.gov/redmine/issues/99415), [101224](https://vlab.noaa.gov/redmine/issues/101224)

---

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Jesse** (Jesse)
Original Date: 2021-04-27T20:12:14Z

---

Take your run-of-the-mill instantaneous value url such as @https://nwis.waterservices.usgs.gov/nwis/iv?endDT=2021-04-06T12%3A00%3A00Z&format=json&parameterCd=00060&sites=01379500&startDT=2021-01-01T00%3A00%3A01Z@ and try to run it against the daily value service with a one letter change, like @https://nwis.waterservices.usgs.gov/nwis/dv?endDT=2021-04-06T12%3A00%3A00Z&format=json&parameterCd=00060&sites=01379500&startDT=2021-01-01T00%3A00%3A01Z@:
> Response: HTTP Status 400 - illegal date-time input for dv-service startDT - time zone not allowed, server=[nadww01]

(And the status is 400, apart from the text shown in the body, so at least that's consistent)

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Jesse** (Jesse)
Original Date: 2021-04-27T20:13:18Z

---

Remove the zone, try this instead: @https://nwis.waterservices.usgs.gov/nwis/dv?endDT=2021-04-06T12%3A00%3A00&format=json&parameterCd=00060&sites=01379500&startDT=2021-01-01T00%3A00%3A01@
> HTTP Status 400 - illegal date-time input for dv-service startDT - hours or minutes not allowed, server=[nadww01]

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Jesse** (Jesse)
Original Date: 2021-04-27T20:14:19Z

---

Ok, remove the times, @https://nwis.waterservices.usgs.gov/nwis/dv?endDT=2021-04-06&format=json&parameterCd=00060&sites=01379500&startDT=2021-01-01@ now we get a response.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Jesse** (Jesse)
Original Date: 2021-04-27T20:17:06Z

---

Does that url work with the instantaneous value API? Kind of, but look what happens to the dates. @https://nwis.waterservices.usgs.gov/nwis/iv?endDT=2021-04-06&format=json&parameterCd=00060&sites=01379500&startDT=2021-01-01@
```<code class="json">
    "queryInfo": {
      "queryURL": "http://nwis.waterservices.usgs.gov/nwis/ivendDT=2021-04-06&format=json&parameterCd=00060&sites=01379500&startDT=2021-01-01",
      "criteria": {
        "locationParam": "[ALL:01379500]",
        "variableParam": "[00060]",
        "timeParam": {
          "beginDateTime": "2021-01-01T00:00:00.000",
          "endDateTime": "2021-04-06T23:59:59.000"
        },
        "parameter": []
      },
      "note": [
        {
          "value": "[ALL:01379500]",
          "title": "filter:sites"
        },
        {
          "value": "[mode=RANGE, modifiedSince=null] interval={INTERVAL[2021-01-01T00:00:00.000-05:00/2021-04-06T23:59:59.000Z]}",
          "title": "filter:timeRange"
        },
</code>
```

It went to @INTERVAL[2021-01-01T00:00:00.000-05:00/2021-04-06T23:59:59.000Z]@

I don't see how that date range can possibly make sense, other than that it expands out to ensure whatever I meant by "2021-01-01" and "2021-04-06" it will capture it.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Jesse** (Jesse)
Original Date: 2021-04-27T20:36:33Z

---

I don't think it will be a huge amount of work.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Jesse** (Jesse)
Original Date: 2021-04-27T20:42:02Z

---

While waiting for an opportunity to deploy, may as well work on this.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2021-04-27T21:27:45Z

---

Will have to look back through some of the history - perhaps #62751 was hyperbole, I don't know, but I do recall some significant smells with the daily values service. Otoh, I'm not sure they are smells that we can mitigate, so I guess we offer access and, from there, users will need to do their own due diligence.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2021-04-27T21:32:32Z

---

One of the main smells that I recall is that the service seemed to offer all sorts of stuff other than "daily values", including instantaneous values.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2021-04-27T21:34:25Z

---

Jesse wrote:
> look what happens to the dates.

#60265-18

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Jesse** (Jesse)
Original Date: 2021-04-27T21:57:33Z

---

Looks like the response body is different:

```
Caused by: wres.io.reading.PreIngestException: Failed to parse the response body from USGS url https://nwis.waterservices.usgs.gov/nwis/dv?endDT=2012-01-01&fo
rmat=json&parameterCd=00060&sites=01013500&startDT=2011-01-01
        at wres.io.reading.waterml.WaterMLBasicSource.deserializeInput(WaterMLBasicSource.java:222)
        at wres.io.reading.waterml.WaterMLBasicSource.ingest(WaterMLBasicSource.java:238)
        at wres.io.reading.waterml.WaterMLBasicSource.saveObservation(WaterMLBasicSource.java:133)
        at wres.io.reading.BasicSource.save(BasicSource.java:39)
        at wres.io.concurrency.IngestSaver.execute(IngestSaver.java:502)
        at wres.io.concurrency.IngestSaver.execute(IngestSaver.java:30)
        at wres.io.concurrency.WRESCallable.call(WRESCallable.java:18)
        ... 4 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "value" (class wres.io.reading.waterml.variable.Option), not m
arked as ignorable (2 known properties: "optionCode", "name"])
 at [Source: (byte[])"{"name":"ns1:timeSeriesResponseType","declaredType":"org.cuahsi.waterml.TimeSeriesResponseType","scope":"javax.xml.bind.JAXBElement$Glob
alScope","value":{"queryInfo":{"queryURL":"http://nwis.waterservices.usgs.gov/nwis/dvendDT=2012-01-01&format=json&parameterCd=00060&sites=01013500&startDT=201
1-01-01","criteria":{"locationParam":"[ALL:01013500]","variableParam":"[00060]","timeParam":{"beginDateTime":"2011-01-01T00:00:00.000","endDateTime":"2012-01-
01T00:00:00.000"},"parameter":[]},"note":[{"valu"[truncated 29162 bytes]; line: 1, column: 2018] (through reference chain: wres.io.reading.waterml.Response["v
alue"]->wres.io.reading.waterml.ResponseValue["timeSeries"]->java.lang.Object[][0]->wres.io.reading.waterml.timeseries.TimeSeries["variable"]->wres.io.reading
.waterml.variable.Variable["options"]->wres.io.reading.waterml.variable.VariableOptions["option"]->java.lang.Object[][0]->wres.io.reading.waterml.variable.Opt
ion["value"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:987)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1974)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1701)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1679)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:330)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:214)
        at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:24)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:214)
        at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:24)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3609)
        at wres.io.reading.waterml.WaterMLBasicSource.deserializeInput(WaterMLBasicSource.java:216)
        ... 10 common frames omitted

```

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Jesse** (Jesse)
Original Date: 2021-04-27T22:00:14Z

---

This also could be due to rigid pojo settings on our side.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Jesse** (Jesse)
Original Date: 2021-04-27T22:01:53Z

---

Not as straightforward as hoped, but I think still within the 16 hour estimate.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2021-12-08T23:00:58Z

---

Comes up periodically. Latest example is #99415. Sounds like we either need a more flexible reader for handling iv and dv together, else a new reader for the dv service.

Bumping priority, fwiw.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2021-12-08T23:10:09Z

---

Oh, and one thing to bear in mind with the dv service, which may or may not affect the estimate: the dv service is more complicated w/r to time scale, but it sounds like it does explicitly qualify it.

See #60265-12.

For streamflow, a mean daily flow is the most likely (perhaps the only) scenario, but that is not necessarily true for other variables.

edit: for the same reason, the time scale is something that can be requested (@statCd@), so that will need to be reconciled with any @existingTimeScale@ (although such declaration is rare).

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Chris** (Chris)
Original Date: 2021-12-09T13:59:52Z

---

I haven't tried this on _every_ location, but, for one reason or another, I found out that you could calculate all of the daily values by indeed just coming up with the mean for all values within a day for a location's flow. I think you'll have a tough time finding stage - I've never seen it available for daily.

I played around with the dashboard to see some daily values and the random selection of about 10 locations only ever showed locations having flow and temperature (not common) for daily values. Within each result set, there's a field of @value/timeseries/#/variable/options/option/#@. In @iv@, it has a name of @Statistic@, but on @dv@ it'll have @value@ that'll be @Minimum@, @Mean@, @Maximum@, or @Median@ (which is rare). I haven't seen anything declaring what span of time the statistic was over, probably because it's tribal knowledge that the user explicitly navigated to the _daily value_ service. The @statCd@ is @all@ by default, so you'll get every stat available for the location. This hasn't really been an issue for flow because there's only ever @Mean@. I imagine it may be a different case if temperature (@00010@) were tried. Here's an example url: https://waterservices.usgs.gov/nwis/dv/?format=json&indent=on&sites=14362000&startDT=2021-12-01&endDT=2021-12-07&siteStatus=all

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2021-12-09T14:15:43Z

---

Yup. There are also some complete examples here (under examples):

https://waterservices.usgs.gov/rest/DV-Service.html

Here is one that explicitly asks for the mean (but you need to know the @stCode@):

https://waterservices.usgs.gov/nwis/dv/?format=waterml&stateCd=ri&parameterCd=00060&siteType=ST&statCd=00003

Right, the time scale duration does seem like tribal knowledge. However, as indicated by the USGS person in #60265-12, it is not totally coherent with the service endpoint because the values could be instantaneous values for some variables, like groundwater. In other words, "daily" can EITHER mean a time scale duration of one day OR it can mean one value per day OR it can mean both!

To be fair, nwis at least makes an effort to qualify the time scale of their data. It still astonishes me how often this information is completely ignored by many time-series data services, else confused/conflated with the timestep of the data. Hey ho.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2023-01-26T14:59:04Z

---

Bumping this because it was mentioned again as a priority for HEFS.

**Comment by james-d-brown** [comment]
Bumping this. I suppose we could leverage this request (the hefs folks do still download the data) to pioneer the new nwis api, which will presumably be consistent when the instantaneous values service is eventually staged, i.e., cutting or eliminating the time to migrate the iv service.

https://api.waterdata.usgs.gov/docs/ogcapi/migration/

**Comment by james-d-brown** [comment]
In other words, any contextual information that may be useful to the low-level reader and requires interaction with other api endpoints of the web service will need to be supplied to the low-level reader on construction. This could include a `Supplier` or `CachingSupplier`, for example, that makes a web request on demand.

**Comment by james-d-brown** [comment]
Progress pushed.

**Comment by james-d-brown** [comment]
I sent a message via their web form, as follows. Let's see what they say, if they do respond:

```
Hello,

I am a private contractor, supporting the U.S. National Weather Service Office of Water Prediction (OWP). I am currently working to migrate one of OWP's evaluation services from your legacy APIs to your latest OGC APIs, beginning with the DV service.

I have a potential bug report, followed by a question. The potential bug concerns the pagination of your results. You include a link to the next page in each response. However, when the original request includes the f=json parameter, the next page linked in the response does not, so it is not usable without modification. Is this a bug?

Regarding the interpretation of the values from the DV service. I believe these values represent a daily timescale recorded from midnight-midnight in local time. Is that correct? 

Since the datetimes are supplied as raw dates in the response ("time"), rather than the offset datetimes used by your IV service (both the legacy and continuous/new variants), the timing information is not transparent and I assume we are supposed to use one of your other endpoints, such as the monitoring location endpoint, to discover the time zone and any local treatment (daylight saving). Is that correct?

Is there a particular reason that the API docs are ambiguous about the meaning of the "daily" values and why offset datetimes are not used? I am wondering whether this is because the meaning of the values is essentially unknown and locally determined (but, as a follow up if true, I wonder how they could be used, in practice, except with an understanding that the timing information is imprecise).

Thanks for your help!

James
```

**Comment by james-d-brown** [comment]
There's a couple of issues that stem from storing values in local times without time-specific zone offsets. 

First, we don't support the declaration of complete time zone information. In other words, we don't support the declaration of data sources that have daylight savings times. Thus, we don't have a hook for passing around this information, specifically as part of the `DataSource`. We merely have a placeholder for a `time_zone_offset`, which is deserialized into a `ZoneOffset`. This is obviously not complete information, rather a constant offset from standard time.

Second, the `monitoring_locations` endpoint also doesn't provide a complete specification, since a time zone abbreviation, such as "EST" is not a time zone. Rather, the widely used standard for representing time zones is the IANA Time Zone Database, which uses a full designation, such as `America/New_York`.

It just so happens that because of a quirk of the Java implementation of a `TimeZone`, we can probably get away with translating a time zone abbreviation to a formal `TimeZone`, but this is not recommended according to the api.

But this doesn't circumvent the fact that we do not support a full declaration of time zone information and hence time-series that are supplied in local time, rather we only (accurately) accept time series that are provided with standard or offset times, together with a declared `time_zone_offset`, where applicable.

Eventually, we will probably need to support the more complete/formal declaration, as well as merely the time zone and, in the more immediate term, we will probably need to provide a placeholder for this in the `DataSource`, if not in the declaration language itself.

**Comment by james-d-brown** [comment]
> It just so happens that because of a quirk of the Java implementation of a `TimeZone`, we can probably get away with translating a time zone abbreviation to a formal `TimeZone`, but this is not recommended according to the api.

Ah, not, in fact. While you can instantiate a `TimeZone` with a zone abbreviation, you don't get the full information, specifically the daylight saving, so it merely functions as a `ZoneOffset` with the raw time zone offset. Sigh, will need a mapping to map from the abbreviated zone offset to the formal IANA name for selected zones that are covered by NWIS.

**Comment by james-d-brown** [comment]
Progress pushed. More on Friday.

**Comment by james-d-brown** [comment]
Need to test this one thoroughly, more so than usual as I don't expect Hank will have a ton of time to UAT this. Draft list of things to check:

- Works for individual locations
- Works for multiple locations in a single declaration
- Works with daylight saving on/off 
- Works for streamflow and river stage, at least
- Responses for fixed queries are idempotent as far as our database ingest, assuming the first ingest has completed and the data has not changed, i.e., the practical effect is that we ingest the same data only once
- Performance considerations, notably the page size. Apparently, the full query is executed on each new page, but the performance recommendation is to construct small queries, so there is seemingly a contradiction there. In any case, will need to test the default, which is currently the largest page size possible. More here: https://api.waterdata.usgs.gov/docs/ogcapi/efficiency/

There may be other things, but that is the initial list.

**Comment by james-d-brown** [comment]
> * Works for individual locations

Example of system test scenario200, adapted to use the DV service:

<img width="800" height="600" alt="Image" src="https://github.com/user-attachments/assets/784ffe46-5a04-4ccd-8f6f-1905b4f5ea88" />

Sample size makes sense, 365x30~=11,000. Completed in a few seconds.

**Comment by james-d-brown** [comment]
> * Responses for fixed queries are idempotent as far as our database ingest, assuming the first ingest has completed and the data has not changed, i.e., the practical effect is that we ingest the same data only once

Database looks the same on repeated evaluations of the adapted scenario200.

**Comment by james-d-brown** [comment]
Oh, another thing to check is that the transition between (one-year) chunks is handled correctly, i.e., seamlessly with no underlaps or overlaps.

**Comment by james-d-brown** [comment]
> Oh, another thing to check is that the transition between (one-year) chunks is handled correctly, i.e., seamlessly with no underlaps or overlaps.

That is handled correctly for the scenario200 example, no underlaps or overlaps.

> * Works with daylight saving on/off

That works for the scenario200 example with DST on, i.e., the default. For this hourly (predicted) dataset, I see the pairs transition by an hour at the expected entry and exit of DST from 8Z to 7Z and vice versa, respectively.

**Comment by james-d-brown** [comment]
> That works for the scenario200 example with DST on, i.e., the default. For this hourly (predicted) dataset, I see the pairs transition by an hour at the expected entry and exit of DST from 8Z to 7Z and vice versa, respectively.

Also works for this:

```
observed:
  sources:
    - uri: https://api.waterdata.usgs.gov/ogcapi/v0/collections/daily/
      interface: usgs nwis
      daylight_savings: false
```

Naturally, this leads to new ingest because all of the observed time-series differ with the default annual chunking.

**Comment by james-d-brown** [comment]
Pared down the adapted scenario200 to just 5 years and compared the statistics when using the DV service directly to the statistics when reading the same data downloaded from the DV service to local geojson files and the results match, so reading from local files is a theoretical possibility, even if it will probably never make sense in practice.

**Comment by james-d-brown** [comment]
Need to create an example with river stage and then look at performance, although performance will be trickier to examine given the (relatively) tiny amount of data involved and the inherent issues with micro-benchmarking.

**Comment by james-d-brown** [comment]
Have improved the docs to clarify the various options and nested options associated with declaring a dataset, including the `parameters` that can be appended to a web service data request.

Next, will look at sanitizing logging to hide any api keys, but that will probably need to wait for tomorrow as I need to write a monthly report tonight.

**Comment by james-d-brown** [comment]
Unit tested.

**Comment by james-d-brown** [comment]
First thing is probably some improved jmc instrumentation for reading events so we can monitor total read times, as distinct from other activities.

**Comment by james-d-brown** [comment]
Oh, I forgot that I added a threshold for some events, notably when monitoring requests to web services:

`@Threshold( "10000 ms" )`

These reads are so fast that they are far from meeting the threshold of PT10S. If we don't set a threshold on these events, we capture a smeg ton of events that are not really "slow" reads.

**Comment by james-d-brown** [comment]
Still looking at how best to add some aggregate monitoring for reads. In the process of identifying that, I am a bit side-tracked with the pipeline that "pulls" on a reader and instigates the reading, i.e., the ingest pipeline. This is in two parts, one for database ingest and one for reading into main memory. 

On the database side, I am not sure the pull is working exactly as expected. Each pull on the stream should be translated by the reader. For the NWIS DV reader, the data is chunked by year, so each pull should translate into one read, which returns one time-series spanning a single year. However, when instrumenting the reading, I get the impression (from the speed returned by the read) that the reading is happening upfront, earlier than expected, probably when an iterator is being created from the stream or shortly thereafter, around here:

```
        // Read one time-series into memory at a time, closing the stream on completion
        try ( timeSeriesTuple )
        {
            Iterator<TimeSeriesTuple> tupleIterator = timeSeriesTuple.iterator();

            int timeSeriesCount = 0;

            while ( tupleIterator.hasNext() )
            {
```

I am going to need to pull on this thread a little, which means getting "sidetracked", but it's important that the pipeline is working as advertised (also important for instrumenting a read or group of reads).

**Comment by james-d-brown** [comment]
Now, in the documentation, the `Stream::iterator` is a terminal operation, so the above may not be very surprising, but I recall looking into this before, which led to the above design, whereby the the `Stream::iterator` is not, in fact, eager in pulling on the stream. Need to look into that again, though.

**Comment by james-d-brown** [comment]
In the mean time, looking at an evaluation that is (probably) just below the rate limit and then one that is above it (well, even a small evaluation will probably trigger the cumulative rate limiting at that point).

**Comment by james-d-brown** [comment]
FWIW, I believe there is (or was) a ticket on our old Redmine backlog for filtering data from NWIS that relates to multiple sensors for a single USGS gage identifier. Would have to check that and see whether it was brought across, but we can either do that or create a new one if the need arises.

**Comment by james-d-brown** [comment]
As a minimum, there is a relevant hook in Redmine 73482, which may provide a test case for UAT of this ticket, which relates to handbook 5 identifier, ABTT2 aka USGS gage identifier, 08155300. The expected behavior is described above.

**Comment by HankHerr-NOAA** [comment]
Okay. So `statistic_id: '00001'` is maximum, so the data is daily maximum. Thanks for the rest of the information. 

A wiki entry letting them know that those services can be used is probably enough, then. 

I can't recall if WRES is able to negotiate the time scales by default or not, so my first attempt to evaluate will not include a `time_scale`. Prepare that declaration now,

Hank

**Comment by HankHerr-NOAA** [comment]
I can get it to succeed using NWM data. Yay!  I need to take a further look at the evaluation and results, digging a bit deeper, but this at least gets me started. I have a short meeting and will return to this afterwards,

Hank

**Comment by HankHerr-NOAA** [comment]
This website is reporting "None" as the values where the time series plots show 0:

https://api.waterdata.usgs.gov/ogcapi/v0/collections/daily/items?lang=en-US&limit=10&properties=id,time_series_id,monitoring_location_id,parameter_code,statistic_id,time,value,unit_of_measure,approval_status,qualifier,last_modified&skipGeometry=false&monitoring_location_id=USGS-01631000&parameter_code=00060&time=2025-12-14T00%3A00%3A00Z%2F2025-12-21T12%3A31%3A12Z

In the pairs, however, I'm see zero value observations. For example:

```
01631000,01631000-5907079,00060,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,PT0S,PT24H,2025-12-15T06:00:00Z,2025-12-16T05:00:00Z,PT23H,0.0000,419.1083
01631000,01631000-5907079,00060,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,PT0S,PT24H,2025-12-15T12:00:00Z,2025-12-16T05:00:00Z,PT17H,0.0000,364.4889
01631000,01631000-5907079,00060,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,PT0S,PT24H,2025-12-15T18:00:00Z,2025-12-16T05:00:00Z,PT11H,0.0000,324.1565
01631000,01631000-5907079,00060,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,PT0S,PT24H,2025-12-16T00:00:00Z,2025-12-16T05:00:00Z,PT5H,0.0000,488.4725
01631000,01631000-5907079,00060,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,PT0S,PT24H,2025-12-16T06:00:00Z,2025-12-17T05:00:00Z,PT23H,0.0000,417.8339
01631000,01631000-5907079,00060,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,PT0S,PT24H,2025-12-16T12:00:00Z,2025-12-17T05:00:00Z,PT17H,0.0000,421.3247
01631000,01631000-5907079,00060,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,PT0S,PT24H,2025-12-16T18:00:00Z,2025-12-17T05:00:00Z,PT11H,0.0000,494.4374
01631000,01631000-5907079,00060,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,PT0S,PT24H,2025-12-17T00:00:00Z,2025-12-17T05:00:00Z,PT5H,0.0000,449.9795
01631000,01631000-5907079,00060,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,PT0S,PT24H,2025-12-17T06:00:00Z,2025-12-18T05:00:00Z,PT23H,0.0000,438.6235
01631000,01631000-5907079,00060,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,PT0S,PT24H,2025-12-17T12:00:00Z,2025-12-18T05:00:00Z,PT17H,0.0000,427.2867
01631000,01631000-5907079,00060,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,PT0S,PT24H,2025-12-17T18:00:00Z,2025-12-18T05:00:00Z,PT11H,0.0000,432.7973
01631000,01631000-5907079,00060,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,2025-12-01T00:00:00Z,2025-12-25T00:00:00Z,PT0S,PT24H,2025-12-18T00:00:00Z,2025-12-18T05:00:00Z,PT5H,0.0000,444.6117
```

@james-d-brown Could it be that the reader is inappropriately handling what the USGS front end reports as "None"?

Hank

**Comment by HankHerr-NOAA** [comment]
I'll continue with the UAT effort next week. My intention is to move onto the RFC forecast evaluation to see if time shifting allows for it to complete. I'll also try HEFS evaluations, some many-feature evaluations, and some checks of the declaration validation and error handling (i.e., playing around with the YAML and seeing what happens).

Thanks,

Hank

**Comment by HankHerr-NOAA** [comment]
One more thing... This first evaluation is establishing a baseline for comparison by using the NWIS IV service. DV would be next.

Hank

**Comment by james-d-brown** [comment]
I can take a look. I am honestly not sure whether or not that is a bug or expected behavior for the metadata endpoint of the OGC web services, assuming that is the problem. It sounds like a potential bug, i.e., not having timing metadata available for some sites. If so, I am a bit reluctant to skip over a bug with a warning. If not, I am a bit surprised, given that it is straightforward static metadata. It could be a bug on our end, though, I will need to investigate. The site is USGS-01585175.

**Comment by james-d-brown** [comment]
Ah, I think I see the potential problem. The cache of feature info is limited to 100 features. I bet the error message includes 100 features and more were requested.

**Comment by HankHerr-NOAA** [comment]
Testing this in staging using WRES GUI posted evaluation 12964 (COWRES job id 9205033041807911139),

Hank

**Comment by HankHerr-NOAA** [comment]
UAT passes,

Hank

**Comment by HankHerr-NOAA** [comment]
@james-d-brown:

Do you have the bandwidth to document use of the daily value API in a wiki? Looking at an example declaration,

```yaml
observed:
  sources:
    - uri: https://api.waterdata.usgs.gov/ogcapi/v0/collections/daily/
      parameters:
        statistic_id: '00003'
      interface: usgs nwis
      daylight_savings: true
  variable: '00060'
  # Central time point, no shift
  time_shift:
      period: 1
      unit: hours
```

If the documentation has already been written, please point me to it; I can't find anything doing some basic searches. I realized that the `statistic_id` and reasoning behind the `time_shift` probably need to be explained, since both will be important in making sure you obtain the desired data and can match the scale of the `predicted` and `baseline`. Rather than explain that in a News item, I'd like to point them to the wiki providing an explanation.

If you don't have the bandwidth, I can try to take a crack at it this afternoon or early tomorrow.

Thanks,

Hank

**Comment by james-d-brown** [comment]
Hank,

It's like I said here:

https://github.com/NOAA-OWP/wres/issues/258#issuecomment-3972909060

I am not totally convinced about documentation or, rather, I have an opinion about the nature of any documentation. 

In general, the use of web services should be transparent and we should NOT duplicate documentation of external web services, the canonical source is the service documentation. We list the services we support. The user looks at the documentation of those services. There is a good argument to join this dot so a user knows *where* to look and, as a convenience, we could perhaps tabulate the known URLs of those services at the time (or version) of writing. In short, we may want a separate (very brief) wiki composed of a tabulation of known web service URLs and service documentation for users. We could link to that from the declaration language wiki as a convenience. This would include only public-facing services, unfortunately.

However, we definitely should not be documenting web service parameters or even generic WRES options (like `daylight_savings` or `time_shift`) in the context of a specific web service. We *should* document the generic WRES options in the declaration language docs and, indeed, they are already documented. Let me know if you ever see an option that is not documented.

Finally, there may be some argument for documenting a "recipe" or whatever whereby we provide a worked example for users, but I think you maintain those docs. It should be noted that `daylight_savings` and `time_shift` and `statistic_id` and even the `interface` are not needed in general when using this service. They *may* satisfy specific use cases (edit: hence "recipe"), but they are not needed, in general.

**Comment by HankHerr-NOAA** [comment]
Okay. Thanks.

My main concern is with `time_shift`. Its not easy to understand when and why that option is needed. I can try to tackle that in a News item. I can also tackle that in a Cookbook recipe in the future. I'll update the draft News item in the VLab ticket shortly.

Hank

**Comment by james-d-brown** [comment]
The `time_shift` is orthogonal to this service, though. It is only needed because of the shape of evaluation being attempted, i.e., evaluating synoptic against non-synoptic times. For example, if you are in a synoptic time zone (i.e., CST in the U.S.), it isn't needed for that user story. 

This may be a common use case, but it really has nothing to do with this web service, which is why it is a generic WRES dataset parameter and not one of the URL `parameters`. You are just as likely to need it in any other context where you are evaluating daily averages. The point where data service requirements meet evaluation requirements are user stories or "examples". I am not saying we should not document examples, I just have a strong opinion about where and how, otherwise you end up with spaghetti documentation that mixes together all sorts of unrelated things.
