### ISSUE TITLE
As a user or system admin, I want improved validation of system settings

### ISSUE THREAD

**Issue by epag** [NOAA-OWP/wres#286]
---

Author Name: **James** (James)
Original Redmine Issue: 99120, https://vlab.noaa.gov/redmine/issues/99120
Original Date: 2021-12-01

---

Given system settings that are exposed to users and system/service administrators
When those settings are tweaked and invalid inputs are provided
Then the user should receive a useful message about what went wrong and how to fix it

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2021-12-01T17:12:04Z

---

Example to the contrary, set any of the thread counts to 0 and you will get something like:

```
java.lang.IllegalArgumentException: null
	at java.base/java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1293)
	at java.base/java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1215)
	at wres.pipeline.Evaluator.evaluate(Evaluator.java:232)
	at wres.pipeline.Evaluator.evaluate(Evaluator.java:183)
	at wres.MainFunctions.execute(MainFunctions.java:134)
	at wres.MainFunctions.call(MainFunctions.java:96)
	at wres.Main.main(Main.java:113)
	at wres.MainLocal.main(MainLocal.java:600)

```

It seems like validation mostly delegates to a commons helper, @StringUtils::isNumeric@, which is fine (it screens for integers), but not sufficient. 

The expected behavior is to log a warning and fall back on (valid) defaults when invalid input is provided. 

To be clear, we don't want an exception because the system can choose reasonable values, ultimately. A logged warning is fine.
