### ISSUE TITLE
As a user, I expect a declaration that contains default (no) metrics and netcdf2 to validate successfully

### ISSUE THREAD

**Issue by james-d-brown** [NOAA-OWP/wres#305]
Given an evaluation like the proposed evaluation in the `README.md`
When I add `output_formats: netcdf2` to the declaration
Then I do not expect a validation error indicating that a score metric must be declared

**Comment by james-d-brown** [comment]
Over-zealous validation that doesn't accept default/no metrics when attempting to reconcile `netcdf2`, which requires score metrics, with the metrics declaration. In practice, default/no metrics will always add score metrics. There is probably a sequencing issue here. In other words, this check should be made after interpolation.

**Comment by james-d-brown** [comment]
This is the error I get:

```
Caused by: wres.config.yaml.DeclarationException: Encountered 1 error(s) in the declared evaluation, which must be fixed:
    - When declaring the 'netcdf' or 'netcdf2' format option, the evaluation must include at least one score metric because these formats only support the writing of verification scores. Please add a score metric to the declaration or remove the unused format from the list of 'output_formats'. A score is a metric that measures quality with a single number, such as the mean square error.
	at wres.config.yaml.DeclarationValidator.notify(DeclarationValidator.java:485)
	at wres.config.yaml.DeclarationValidator.validate(DeclarationValidator.java:316)
	at wres.config.yaml.DeclarationFactory.from(DeclarationFactory.java:267)
	at wres.config.MultiDeclarationFactory.from(MultiDeclarationFactory.java:92)
	at wres.pipeline.Evaluator.evaluate(Evaluator.java:161)
```

**Comment by james-d-brown** [comment]
Have that fixed, creating a unit test.
