### ISSUE TITLE
As a developer, I want the JUnit tests to complete on the NWC-hosted Linux development VM.

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#306]
It appears to run very slowly (not quite stuck) when it reaches `wres.io.database.QueryTest`. Here is a snippet of what I see after letting it run for over an hour:

```
    2024-09-06T14:18:46.603+0000  [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Fill pool skipped, pool has sufficient level or currently being filled.
    2024-09-06T14:19:16.603+0000  [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
    2024-09-06T14:19:16.603+0000  [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Fill pool skipped, pool has sufficient level or currently being filled.
    2024-09-06T14:19:46.604+0000  [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
    2024-09-06T14:19:46.604+0000  [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Fill pool skipped, pool has sufficient level or currently being filled.
    2024-09-06T14:20:16.604+0000  [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
    2024-09-06T14:20:16.604+0000  [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Fill pool skipped, pool has sufficient level or currently being filled.
    2024-09-06T14:20:46.605+0000  [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
    2024-09-06T14:20:46.605+0000  [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Fill pool skipped, pool has sufficient level or currently being filled.
<=======------> 58% EXECUTING [1h 13m 32s]
> :wres-io:test > 0 tests completed
> :wres-io:test > Executing test wres.io.database.QueryTest

```

Thanks,

Hank

**Comment by HankHerr-NOAA** [comment]
Before I deploy, I think I need to address this ticket. It would be awkward to deploy to a Linux VM when we don't really know that unit tests complete on a Linux VM.

I'm pulling the latest and running a `./gradlew build` now.

Hank

**Comment by epag** [comment]
If you want to do this before a deploy feel free, but I don't think this is necessary. We use a package manager so if stuff starts failing when we run it on linux as opposed to windows (Also github uses a linux distro as well), then we have a much larger problem. 

I think you are the only one that has even been able to build on the production boxes so this has not been something that has been verified any time that it isn't you deploying.

**Comment by HankHerr-NOAA** [comment]
Okay. I'll at least take a look and see what it points to and then decide.  

In this case, I looked at a [recent build action](https://productionresultssa15.blob.core.windows.net/actions-results/5fe58a50-b57d-4e69-b101-d7e9e6823dca/workflow-job-run-ca395085-040a-526b-2ce8-bdc85f692774/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-09-10T16%3A56%3A35Z&sig=xt7xou7NIJbSlbLRnAL1s7S%2BH0xrtBFu2IDwtVw%2FlWY%3D&ske=2024-09-11T02%3A24%3A41Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-09-10T14%3A24%3A41Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-05-04&sp=r&spr=https&sr=b&st=2024-09-10T16%3A46%3A30Z&sv=2024-05-04), and spotted this sequence for `QueryTest` in the stdout log:

```
2024-09-09T17:40:52.8688136Z QueryTest > simpleExecuteTest STANDARD_OUT
2024-09-09T17:40:52.8689938Z     2024-09-09T17:40:52.843+0000  [Test worker] DEBUG wres.system.DatabaseSettings - Failed to load the database driver class org.mariadb.jdbc.Driver.
2024-09-09T17:40:52.8692493Z     2024-09-09T17:40:52.845+0000  [Test worker] DEBUG wres.system.DatabaseSettings - Failed to load the database driver class org.mariadb.jdbc.Driver.
2024-09-09T17:40:52.8695158Z     2024-09-09T17:40:52.845+0000  [Test worker] DEBUG wres.system.DatabaseSettings - Failed to load the database driver class org.sqlite.JDBC.
2024-09-09T17:40:52.9683045Z     2024-09-09T17:40:52.932+0000  [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=1, active=0, idle=1, waiting=0)
2024-09-09T17:40:52.9686430Z     2024-09-09T17:40:52.935+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection conn2: url=jdbc:h2:mem:wres.io.database.QueryTest user=
2024-09-09T17:40:53.0683213Z     2024-09-09T17:40:52.966+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After adding stats (total=2, active=0, idle=2, waiting=0)
2024-09-09T17:40:53.0686399Z     2024-09-09T17:40:52.969+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection conn3: url=jdbc:h2:mem:wres.io.database.QueryTest user=
2024-09-09T17:40:53.0688772Z     2024-09-09T17:40:53.000+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After adding stats (total=3, active=0, idle=3, waiting=0)
2024-09-09T17:40:53.0691284Z     2024-09-09T17:40:53.002+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection conn4: url=jdbc:h2:mem:wres.io.database.QueryTest user=
2024-09-09T17:40:53.0694037Z     2024-09-09T17:40:53.032+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After adding stats (total=4, active=0, idle=4, waiting=0)
2024-09-09T17:40:53.0696786Z     2024-09-09T17:40:53.034+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection conn5: url=jdbc:h2:mem:wres.io.database.QueryTest user=
2024-09-09T17:40:53.0699497Z     2024-09-09T17:40:53.064+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After adding stats (total=5, active=0, idle=5, waiting=0)
2024-09-09T17:40:53.0702493Z     2024-09-09T17:40:53.065+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection conn6: url=jdbc:h2:mem:wres.io.database.QueryTest user=
2024-09-09T17:40:53.1682590Z     2024-09-09T17:40:53.096+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After adding stats (total=6, active=0, idle=6, waiting=0)
2024-09-09T17:40:53.1685522Z     2024-09-09T17:40:53.097+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection conn7: url=jdbc:h2:mem:wres.io.database.QueryTest user=
2024-09-09T17:40:53.1688814Z     2024-09-09T17:40:53.128+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After adding stats (total=7, active=0, idle=7, waiting=0)
2024-09-09T17:40:53.1691667Z     2024-09-09T17:40:53.129+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection conn8: url=jdbc:h2:mem:wres.io.database.QueryTest user=
2024-09-09T17:40:53.2683168Z     2024-09-09T17:40:53.159+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After adding stats (total=8, active=0, idle=8, waiting=0)
2024-09-09T17:40:53.2687259Z     2024-09-09T17:40:53.161+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection conn9: url=jdbc:h2:mem:wres.io.database.QueryTest user=
2024-09-09T17:40:53.2690645Z     2024-09-09T17:40:53.191+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After adding stats (total=9, active=0, idle=9, waiting=0)
2024-09-09T17:40:53.2694374Z     2024-09-09T17:40:53.192+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection conn10: url=jdbc:h2:mem:wres.io.database.QueryTest user=
2024-09-09T17:40:53.2698132Z     2024-09-09T17:40:53.223+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After adding stats (total=10, active=0, idle=10, waiting=0)
2024-09-09T17:40:53.9685787Z     2024-09-09T17:40:53.944+0000  [Test worker] ERROR h2database - jdbc[4] exception
2024-09-09T17:40:53.9687844Z     org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "DATABASECHANGELOGLOCK" not found; SQL statement:
2024-09-09T17:40:53.9689682Z     SELECT COUNT(*) FROM PUBLIC.DATABASECHANGELOGLOCK [42102-232]
2024-09-09T17:40:53.9691140Z     	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
2024-09-09T17:40:53.9692787Z     	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
2024-09-09T17:40:53.9813082Z     	at org.h2.message.DbException.get(DbException.java:223)
2024-09-09T17:40:53.9814162Z     	at org.h2.message.DbException.get(DbException.java:199)
...SNIP...
2024-09-09T17:40:53.9906898Z     	at liquibase.Liquibase.update(Liquibase.java:188)
2024-09-09T17:40:53.9907727Z     	at liquibase.Liquibase.update(Liquibase.java:175)
2024-09-09T17:40:53.9908772Z     	at wres.io.database.TestDatabase.createProjectTable(TestDatabase.java:171)
2024-09-09T17:40:53.9910001Z     	at wres.io.database.QueryTest.simpleExecuteTest(QueryTest.java:159)
...SNIP...
2024-09-09T17:40:54.0799619Z     	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
2024-09-09T17:40:54.0801202Z     	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
2024-09-09T17:40:54.1683101Z     Running Changeset: database/wres.Project_v5.xml::wres.Project v2.0 - Create project dataset table for most dbs.::Jesse Bickel
2024-09-09T17:40:54.1684336Z 
2024-09-09T17:40:54.1684531Z     UPDATE SUMMARY
2024-09-09T17:40:54.1685031Z     Run:                          1
2024-09-09T17:40:54.1685645Z     Previously run:               0
2024-09-09T17:40:54.1686233Z     Filtered out:                 0
2024-09-09T17:40:54.1686886Z     -------------------------------
2024-09-09T17:40:54.1687444Z     Total change sets:            1
2024-09-09T17:40:54.1687846Z 
2024-09-09T17:40:54.1688214Z     Liquibase: Update has been successful. Rows affected: 1
2024-09-09T17:40:54.2681862Z [0K[1mwres.io.database.QueryTest[m
2024-09-09T17:40:54.2682667Z 
2024-09-09T17:40:54.2683561Z [0K[1m  Test [22msimpleExecuteTest[32m PASSED[33m (1.3s)[m
```

Here is what I see from a Linux VM:

```
QueryTest > simpleExecuteTest STANDARD_OUT
    2024-09-10T16:35:10.229+0000  [Test worker] DEBUG wres.system.DatabaseSettings - Failed to load the database driver class org.mariadb.jdbc.Driver.
    2024-09-10T16:35:10.230+0000  [Test worker] DEBUG wres.system.DatabaseSettings - Failed to load the database driver class org.mariadb.jdbc.Driver.
    2024-09-10T16:35:10.230+0000  [Test worker] DEBUG wres.system.DatabaseSettings - Failed to load the database driver class org.sqlite.JDBC.
    2024-09-10T16:35:10.234+0000  [Test worker] WARN wres.system.SettingsFactory - Could not find password for localhost:5432:wres:wres in pgpass file.
    2024-09-10T16:35:10.321+0000  [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=1, active=0, idle=1, waiting=0)
    2024-09-10T16:35:10.322+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection conn2: url=jdbc:h2:mem:wres.io.database.QueryTest user=
    2024-09-10T16:35:10.353+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After adding stats (total=2, active=0, idle=2, waiting=0)
    2024-09-10T16:35:10.354+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection conn3: url=jdbc:h2:mem:wres.io.database.QueryTest user=
    2024-09-10T16:35:10.385+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After adding stats (total=3, active=0, idle=3, waiting=0)
    2024-09-10T16:35:10.386+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection conn4: url=jdbc:h2:mem:wres.io.database.QueryTest user=
    2024-09-10T16:35:10.420+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After adding stats (total=4, active=0, idle=4, waiting=0)
    2024-09-10T16:35:10.422+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection conn5: url=jdbc:h2:mem:wres.io.database.QueryTest user=
    2024-09-10T16:35:10.452+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After adding stats (total=5, active=0, idle=5, waiting=0)
    2024-09-10T16:35:10.454+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection conn6: url=jdbc:h2:mem:wres.io.database.QueryTest user=
    2024-09-10T16:35:10.484+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After adding stats (total=6, active=0, idle=6, waiting=0)
    2024-09-10T16:35:10.485+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection conn7: url=jdbc:h2:mem:wres.io.database.QueryTest user=
    2024-09-10T16:35:10.516+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After adding stats (total=7, active=0, idle=7, waiting=0)
    2024-09-10T16:35:10.517+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection conn8: url=jdbc:h2:mem:wres.io.database.QueryTest user=
    2024-09-10T16:35:10.547+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After adding stats (total=8, active=0, idle=8, waiting=0)
    2024-09-10T16:35:10.548+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection conn9: url=jdbc:h2:mem:wres.io.database.QueryTest user=
    2024-09-10T16:35:10.579+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After adding stats (total=9, active=0, idle=9, waiting=0)
    2024-09-10T16:35:10.580+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection conn10: url=jdbc:h2:mem:wres.io.database.QueryTest user=
    2024-09-10T16:35:10.610+0000  [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After adding stats (total=10, active=0, idle=10, waiting=0)
    2024-09-10T16:35:40.322+0000  [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
    2024-09-10T16:35:40.322+0000  [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Fill pool skipped, pool has sufficient level or currently being filled.
    2024-09-10T16:36:10.322+0000  [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
    2024-09-10T16:36:10.323+0000  [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Fill pool skipped, pool has sufficient level or currently being filled.
    2024-09-10T16:36:40.323+0000  [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
...
```

The "Fill" and "Pool" messages then repeat over and over.

Is the exception in GitHub expected? Let me take in Jenkins at the same test and see what logging is noticed.

Hank

**Comment by HankHerr-NOAA** [comment]
Yes, the GitHub output matches what we see for Jenkins build 5317, the most recent.

The exception appears to be coming out of Liquibase, but what I'm wondering is if the unit test is actually even doing anything when it is a "success" in GitHub.  Since the test runs in Eclipse, I'm going to add some debug statements to see if there is any evidence of the test doing anything after the call to, `QueryTest.testDatabase.createProjectTable( this.liquibaseDatabase );`.

Hank

**Comment by HankHerr-NOAA** [comment]
Yes, it makes it past that point. So whatever stack trace I'm seeing, it doesn't mean the test halts.  

Returning my focus to Linux, I'm going to add some debug statements to see if I can determine the exact code line in the test where it slows to a crawl (presumably, in setting up the H2 database using Liquibase, but we'll see),

Hank

**Comment by HankHerr-NOAA** [comment]
I confirmed that its not getting past the first call in the text:

```java
        QueryTest.testDatabase.createProjectTable( this.liquibaseDatabase );
```

However, I can't get any more information than that. I'm not sure what is going on. 

I have a test run on-going to see if it ever fails out. I'm just going to let it run until the end of the day. In the mean time, I'm going to start looking at dependency updates for the next deployment.

Hank

**Comment by HankHerr-NOAA** [comment]
After 2h 47m, the QueryTest still did not stop. I don't know what its doing, but its clearly stuck.  

I may take Evan up on his recommendation to not worry about it for 6.26. 

Hank

**Comment by HankHerr-NOAA** [comment]
Since running the tests locally would make it easier to handle dependency updates, I'm taking another crack at this ticket until my 10am meeting.

I've isolated the freeze to being in this method during the `new` call:

```java
    public void createProjectTable( Database liquibaseDatabase )
            throws LiquibaseException
    {
        Liquibase liquibase = new Liquibase( "database/wres.Project_v5.xml",
                                             new ClassLoaderResourceAccessor(),
                                             liquibaseDatabase );
        liquibase.update( new Contexts() );
    }
```

I base that on debug print statements at the top, bottom, and middle, and only the top print showing. 

I modified the file `wres-io/testNonsrc/logback-test.xml` so that liquibase is logged at a debug level, but that showed no log output.

Hank

**Comment by HankHerr-NOAA** [comment]
I'm at a loss as to what is going on.  It works in GitHub, on my laptop via Eclipse, and presumably for everyone else. But, on nwcal-ised-dev1, the test gets stuck. I can't get any additional logging from liquibase after editing the test logback file, so I can't trace what is taking so long. I also upped the memory for `gradlew` in case that is somehow limiting it. Nothing worked.

I'm running the tests now using `nwcal-wres-ti01`. If I can't get that to work, then I'm going to leave this on hold, disable the `QueryTest`, and do dependency updates without that test running locally. 

Hank

**Comment by HankHerr-NOAA** [comment]
It is making more progress, but its crawling.

Slowness like this is generally caused by one of two things, in my experience: massive garbage collection due to insufficient -Xmx or McAfee. Given the -Xmx is the default and appears to be enough in GitHub and on our laptops, I'm thinking McAfee maybe slowing me to a crawl. I have a way to test that: run the build in a container. However, that will take a bit to set up. I'll see if I can do that after lunch.

Hank

**Comment by HankHerr-NOAA** [comment]
I don't appear to have the ability to run the build inside of a Docker container. When I start a JDK 17 container, `./gradlew build` just sits there and does nothing.

Hank

**Comment by HankHerr-NOAA** [comment]
I did some more investigating, including creating images that use Gradle was the basis, but I haven't had any luck triggering the build I want to trigger and I feel like I'm just spinning my wheels. 

Without an effective way to build and test on the NWC VMs, I'm left with the alternative of creating a branch and relying on GitHub to run my unit tests.  That is going to be a pain in the rear.

I'm leaving this ticket open, but, if McAfee is the cause, I doubt a solution is going to present itself anytime soon.

Hank

**Comment by HankHerr-NOAA** [comment]
I removed this from 6.26.  Focusing on the dependency updates,

Hank

**Comment by HankHerr-NOAA** [comment]
I confirmed that this was a McAfee issue. I asked ITSG to adjust the rules on my development machine the same way they updated the behavior on the production and staging machines. When that was done, the unit tests were able to complete in 4m 27s.

No code change is needed for this ticket. I'm marking this as done. If there is a better state for it, let me know.

Hank
