### ISSUE TITLE
As a user, if I have an evaluation with many features and sampling uncertainty, but one fails due to insufficient data to calculate the optimal block size, I don't want the evaluation to fail

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#342]
See VLab #120579-257.  The evaluation uses WRES RFC forecasts spanning a year for all NWRFC locations returned by WRDS. The exception occurred for one pool after many features and pools were already complete and led to an overall failure of the evaluation. I was able to reproduce the problem using a two feature run which I'll share in the first comment. The complete exception that led to the evaluation failure is below.

More in comment 1,

Hank

==============================

```
2024-10-18T03:24:35.497+0000  [pool-23-thread-1] INFO EvaluationService - The evaluation failed with the following stack trace: 
wres.pipeline.InternalWresException: Could not complete project execution
    at wres.pipeline.Evaluator.evaluate(Evaluator.java:406)
    at wres.pipeline.Evaluator.evaluate(Evaluator.java:178)
    at wres.Functions.evaluate(Functions.java:135)
    at wres.server.EvaluationService.lambda$startEvaluation$2(EvaluationService.java:695)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: wres.pipeline.WresProcessingException: Encountered an error while processing evaluation 'IYou7J-E__bN5DhqYF7_AZ5Emh4': 
    at wres.pipeline.Evaluator.evaluate(Evaluator.java:835)
    at wres.pipeline.Evaluator.evaluate(Evaluator.java:377)
    ... 7 common frames omitted
Caused by: java.util.concurrent.CompletionException: wres.datamodel.bootstrap.InsufficientDataForResamplingException: Insufficient data to calculate the optimal block size for the stationary bootstrap. The time-series examined had the following metadata: [TimeSeriesMetadata[timeScale=[INSTANTANEOUS],referenceTimes={ISSUED_TIME=2024-06-16T18:23:00Z},variableName=00060,feature=Feature[name=13172500,description=SNAKE RIVER NR MURPHY ID,srid=4326,wkt=POINT ( -116.3906389 43.25481389 )],unit=ft3/s], TimeSeriesMetadata[timeScale=[INSTANTANEOUS],referenceTimes={ISSUED_TIME=2024-06-16T22:22:00Z},variableName=00060,feature=Feature[name=13172500,description=SNAKE RIVER NR MURPHY ID,srid=4326,wkt=POINT ( -116.3906389 43.25481389 )],unit=ft3/s]]
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
    ... 3 common frames omitted
Caused by: wres.datamodel.bootstrap.InsufficientDataForResamplingException: Insufficient data to calculate the optimal block size for the stationary bootstrap. The time-series examined had the following metadata: [TimeSeriesMetadata[timeScale=[INSTANTANEOUS],referenceTimes={ISSUED_TIME=2024-06-16T18:23:00Z},variableName=00060,feature=Feature[name=13172500,description=SNAKE RIVER NR MURPHY ID,srid=4326,wkt=POINT ( -116.3906389 43.25481389 )],unit=ft3/s], TimeSeriesMetadata[timeScale=[INSTANTANEOUS],referenceTimes={ISSUED_TIME=2024-06-16T22:22:00Z},variableName=00060,feature=Feature[name=13172500,description=SNAKE RIVER NR MURPHY ID,srid=4326,wkt=POINT ( -116.3906389 43.25481389 )],unit=ft3/s]]
    at wres.datamodel.bootstrap.BootstrapUtilities.lambda$getOptimalBlockSizeForStationaryBootstrap$16(BootstrapUtilities.java:459)
    at java.base/java.util.Optional.orElseThrow(Optional.java:403)
    at wres.datamodel.bootstrap.BootstrapUtilities.getOptimalBlockSizeForStationaryBootstrap(BootstrapUtilities.java:459)
    at wres.datamodel.bootstrap.BootstrapUtilities.getOptimalBlockSizeForStationaryBootstrap(BootstrapUtilities.java:62)
    at wres.pipeline.pooling.PoolProcessor.getSamplingUncertaintyStatistics(PoolProcessor.java:555)
    at wres.pipeline.pooling.PoolProcessor.createStatistics(PoolProcessor.java:492)
    at wres.pipeline.pooling.PoolProcessor.get(PoolProcessor.java:151)
    at wres.pipeline.pooling.PoolProcessor.get(PoolProcessor.java:60)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
    ... 3 common frames omitted
```

**Comment by HankHerr-NOAA** [comment]
The declaration to reproduce is below. The `predicted` data is attached. Please let me know if you are able to reproduce the problem.

Thanks,

Hank

[GitHub342_120579_DONO3_SNAI1.json.gz](https://github.com/user-attachments/files/17435797/GitHub342_120579_DONO3_SNAI1.json.gz)

=================

```yaml
label: 120579 NWRFC RFC Forecasts
observed:
  label: USGS NWIS Streamflow Observations
  sources:
    uri: https://nwis.waterservices.usgs.gov/nwis/iv
    interface: usgs nwis
  variable: "00060"
  type: observations
predicted:
  label: RFC_AHPS_Flow_90day_CSV
  sources:
    uri: http://[WRDS]/api/rfc_forecast/v2.0/forecast/streamflow
    interface: wrds ahps
  variable: QR
  type: single valued forecasts
feature_service:
  uri: https://[WRDS]/api/location/v3.0/metadata
#  group: rfc
#  value: nwrfc
features:
  - {observed: '10396000', predicted: 'DONO3'}
  - {observed: '13172500', predicted: 'SWAI1'}
unit: ft3/s
reference_dates:
  minimum: 2023-06-26T00:00:00Z
  maximum: 2024-06-26T00:00:00Z
valid_dates:
  minimum: 2023-06-26T00:00:00Z
  maximum: 2024-06-26T00:00:00Z
lead_times:
  minimum: 0
  maximum: 240
  unit: hours
lead_time_pools:
  period: 6
  frequency: 6
  unit: hours
sampling_uncertainty:
  sample_size: 1000
  quantiles: [0.05,0.5,0.95]
metrics:
  - volumetric efficiency
  - mean absolute error
  - mean error
  - coefficient of determination
  - root mean square error
  - mean square error
  - bias fraction
  - sample size
  - root mean square error normalized
  - mean square error skill score normalized
output_formats:
  - csv2
  - png
```

**Comment by james-d-brown** [comment]
Reproduced:

```
Caused by: java.util.concurrent.CompletionException: wres.datamodel.bootstrap.InsufficientDataForResamplingException: Insufficient data to calculate the optimal block size for the stationary bootstrap. The time-series examined had the following metadata: [TimeSeriesMetadata[timeScale=[INSTANTANEOUS],referenceTimes={ISSUED_TIME=2024-06-16T22:22:00Z},variableName=00060,feature=Feature[name=13172500,description=SNAKE RIVER NR MURPHY ID,srid=4326,wkt=POINT ( -116.3906389 43.25481389 )],unit=ft3/s], TimeSeriesMetadata[timeScale=[INSTANTANEOUS],referenceTimes={ISSUED_TIME=2024-06-16T18:23:00Z},variableName=00060,feature=Feature[name=13172500,description=SNAKE RIVER NR MURPHY ID,srid=4326,wkt=POINT ( -116.3906389 43.25481389 )],unit=ft3/s]]
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: wres.datamodel.bootstrap.InsufficientDataForResamplingException: Insufficient data to calculate the optimal block size for the stationary bootstrap. The time-series examined had the following metadata: [TimeSeriesMetadata[timeScale=[INSTANTANEOUS],referenceTimes={ISSUED_TIME=2024-06-16T22:22:00Z},variableName=00060,feature=Feature[name=13172500,description=SNAKE RIVER NR MURPHY ID,srid=4326,wkt=POINT ( -116.3906389 43.25481389 )],unit=ft3/s], TimeSeriesMetadata[timeScale=[INSTANTANEOUS],referenceTimes={ISSUED_TIME=2024-06-16T18:23:00Z},variableName=00060,feature=Feature[name=13172500,description=SNAKE RIVER NR MURPHY ID,srid=4326,wkt=POINT ( -116.3906389 43.25481389 )],unit=ft3/s]]
	at wres.datamodel.bootstrap.BootstrapUtilities.lambda$getOptimalBlockSizeForStationaryBootstrap$16(BootstrapUtilities.java:459)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at wres.datamodel.bootstrap.BootstrapUtilities.getOptimalBlockSizeForStationaryBootstrap(BootstrapUtilities.java:459)
	at wres.datamodel.bootstrap.BootstrapUtilities.getOptimalBlockSizeForStationaryBootstrap(BootstrapUtilities.java:62)
	at wres.pipeline.pooling.PoolProcessor.getSamplingUncertaintyStatistics(PoolProcessor.java:555)
	at wres.pipeline.pooling.PoolProcessor.createStatistics(PoolProcessor.java:492)
	at wres.pipeline.pooling.PoolProcessor.get(PoolProcessor.java:151)
	at wres.pipeline.pooling.PoolProcessor.get(PoolProcessor.java:60)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
```

**Comment by james-d-brown** [comment]
Problem here is an inconsistency between how a guard determines whether the sample size is sufficient (the total number of time-series events) versus how the guarded method determines the minimum sample size (the total number of unique time-series event times). Need to render those two things equivalent, specifically the guard needs to be fixed.

**Comment by HankHerr-NOAA** [comment]
Exception no longer occurs. This passes UAT,

Hank
