### ISSUE TITLE
As a user, if I include sampling uncertainty in an evaluation of freezing level with precip as a covariate, I don't expect a NoSuchElementException

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#39]
There is probably a good reason for the failure, but I'm guessing a NoSuchElementException is not the way to report it.  Here is the exception:

```
wres.pipeline.InternalWresException: Could not complete project execution
	at wres.pipeline.Evaluator.evaluate(Evaluator.java:406)
	at wres.pipeline.Evaluator.evaluate(Evaluator.java:178)
	at wres.Functions.evaluate(Functions.java:135)
	at wres.server.EvaluationService.lambda$startEvaluation$2(EvaluationService.java:698)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: wres.pipeline.WresProcessingException: Encountered an error while processing evaluation 'ViZVhA45aN4yZzODq0s1wRfu2ZQ': 
	at wres.pipeline.Evaluator.evaluate(Evaluator.java:827)
	at wres.pipeline.Evaluator.evaluate(Evaluator.java:377)
	... 7 common frames omitted
Caused by: java.util.concurrent.CompletionException: java.util.NoSuchElementException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	... 3 common frames omitted
Caused by: java.util.NoSuchElementException: null
	at java.base/java.util.TreeMap.key(TreeMap.java:1602)
	at java.base/java.util.TreeMap.firstKey(TreeMap.java:291)
	at java.base/java.util.TreeSet.first(TreeSet.java:391)
	at java.base/java.util.Collections$UnmodifiableSortedSet.first(Collections.java:1201)
	at wres.datamodel.bootstrap.BootstrapPool.lambda$new$0(BootstrapPool.java:215)
	at java.base/java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:473)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.base/java.util.TimSort.sort(TimSort.java:234)
	at java.base/java.util.Arrays.sort(Arrays.java:1307)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1721)
	at wres.datamodel.bootstrap.BootstrapPool.<init>(BootstrapPool.java:222)
	at wres.datamodel.bootstrap.BootstrapPool.of(BootstrapPool.java:66)
	at wres.datamodel.bootstrap.StationaryBootstrapResampler.<init>(StationaryBootstrapResampler.java:851)
	at wres.datamodel.bootstrap.StationaryBootstrapResampler.of(StationaryBootstrapResampler.java:125)
	at wres.pipeline.pooling.PoolProcessor.getSamplingUncertaintyStatistics(PoolProcessor.java:579)
	at wres.pipeline.pooling.PoolProcessor.createStatistics(PoolProcessor.java:492)
	at wres.pipeline.pooling.PoolProcessor.get(PoolProcessor.java:151)
	at wres.pipeline.pooling.PoolProcessor.get(PoolProcessor.java:60)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 common frames omitted
```

The declaration is below. Its the freezing level evaluation used to illustrate covariates for the upcoming QPR with sampling uncertainty added.  The data to reproduce should already be available since that was the same evaluation used to test covariates.

Thanks,

Hank

====================

```yml
label: QPR eval with covariates
observed:
  sources: .../WWBC1HUF.ZELV
  time_zone_offset: -6
predicted:
  sources: .../WWBC1HUF.zelv.hindcasts.tgz
covariates:
  - sources: .../WWBC1HUF.MRGHO.MAP06
    minimum: 0.01
    time_zone_offset: -6
features:
  - {observed: WWBC1HUF, predicted: WWBC1HUF}
lead_times:
  minimum: 0
  maximum: 368
  unit: hours
lead_time_pools:
  period: 6
  unit: hours
season:
  minimum_day: 1
  minimum_month: 12
  maximum_day: 31
  maximum_month: 3
probability_thresholds:
  values: [0.25]
  operator: greater equal
  apply_to: observed
sampling_uncertainty:
  sample_size: 500
  quantiles: [0.05,0.95]
duration_format: hours
decimal_format: '#0.000000'
output_formats:
  - csv2
  - pairs
  - png
```

**Comment by HankHerr-NOAA** [comment]
Worth noting... I have a second evaluation on-going that does not include `covariates`. Its processed 26 of 61 pools so far.

Hank

**Comment by james-d-brown** [comment]
I don't see the data staged in the g-drive dir for large datasets, so we should probably upload there to avoid confusion.

**Comment by HankHerr-NOAA** [comment]
Will do. I had assumed that you already had the data, but perhaps not. Regardless, its probably good regardless to share via Google Drive.

I need to step away, but should have that data uploaded in about 20 minutes.

Hank

**Comment by james-d-brown** [comment]
I will have it somewhere, but it is better to be certain that we're using the same data as the original ticket on vlab is several years old.

**Comment by HankHerr-NOAA** [comment]
The files are available in the usual WRES Redmine Tickets Large Data Sets folder, subdirectory GitHub_39.

Hank

**Comment by HankHerr-NOAA** [comment]
I confirmed that the evaluation without covariates succeeds and includes sampling uncertainty whiskers in the plot of the BSS.

Thanks,

Hank

**Comment by james-d-brown** [comment]
Thanks, will take a look tomorrow. Probably quite a simple thing. Sounds like there are some empty time-series (after covariate filtering) that are not being handled properly.

**Comment by james-d-brown** [comment]
Reproduced:

Caused by: java.util.NoSuchElementException: null
	at java.base/java.util.TreeMap.key(TreeMap.java:1602)
	at java.base/java.util.TreeMap.firstKey(TreeMap.java:291)
	at java.base/java.util.TreeSet.first(TreeSet.java:391)
	at java.base/java.util.Collections$UnmodifiableSortedSet.first(Collections.java:1201)
	at wres.datamodel.bootstrap.BootstrapPool.lambda$new$0(BootstrapPool.java:215)
	at java.base/java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:473)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.base/java.util.TimSort.sort(TimSort.java:234)
	at java.base/java.util.Arrays.sort(Arrays.java:1307)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1721)
	at wres.datamodel.bootstrap.BootstrapPool.<init>(BootstrapPool.java:222)
	at wres.datamodel.bootstrap.BootstrapPool.of(BootstrapPool.java:66)
	at wres.datamodel.bootstrap.StationaryBootstrapResampler.<init>(StationaryBootstrapResampler.java:851)
	at wres.datamodel.bootstrap.StationaryBootstrapResampler.of(StationaryBootstrapResampler.java:125)
	at wres.pipeline.pooling.PoolProcessor.getSamplingUncertaintyStatistics(PoolProcessor.java:579)
	at wres.pipeline.pooling.PoolProcessor.createStatistics(PoolProcessor.java:492)
	at wres.pipeline.pooling.PoolProcessor.get(PoolProcessor.java:151)
	at wres.pipeline.pooling.PoolProcessor.get(PoolProcessor.java:60)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)

**Comment by james-d-brown** [comment]
Issue is indeed related to the handling of empty time-series. which are common when filtered by covariates (in this case).

As to whether the estimates of sampling uncertainty are robust with so many empty time-series and partially filtered time-series, that is a separate question, but it should mechanically work, so fixing that.

**Comment by james-d-brown** [comment]
Have the fix locally.
