### ISSUE TITLE
Race condition on closing stale evaluations

### ISSUE THREAD

**Issue by epag** [NOAA-OWP/wres#50]
We have a timeout thread in our embedded server that forces closure of evaluations to prevent stale/unresponsive evaluations from clogging our server. This timeout thread checks ever 1 minute that the status of the evaluation is either IN_PROGRESS or CLOSED. If the evaluation is closed, but the server is still occupied we close and clean up any evaluations on the server to free it up.

There is a very small chance that the timeout thread checks the status of the evaluation near the exact millisecond that the evaluation finishes, but BEFORE the shim calls for the results. This means that the evaluation is cleaned up BEFORE we are able to report out the results. 

https://github.com/NOAA-OWP/wres/blob/4b80685bc10b080ecaac73ea55e561be6d53244d/src/wres/server/EvaluationService.java#L937-L961

**Comment by epag** [comment]
We can see from the logs that the timeout thread was activated and when we attempt to get the results it is no longer there. IE the thread cleans up the evaluation before we can get its results

```
INFO JobStandardStreamMessenger 2024-07-18T22:25:57.843+0000 INFO EvaluationService Evaluation with internal ID 2934318159869208864 and evaluation ID of aY7VEKdVxydAOSeiuxUmdcUYphI has returned
INFO JobStandardStreamMessenger 2024-07-18T22:25:58.020+0000 INFO EvaluationService Timeout thread closing project
INFO JobStandardStreamMessenger 2024-07-18T22:25:58.022+0000 INFO EvaluationService Closing Evaluation
INFO JobStandardStreamMessenger Finished sending STDERR for job 7433671553109845363
INFO JobStandardStreamMessenger Finished sending STDOUT for job 7433671553109845363
WARN JobStatusMessenger Failed to create channel, declare exchange, or get status.
java.io.IOException: Unable to get status with given ID
        at wres.worker.JobStatusMessenger.getEvaluationStatus(JobStatusMessenger.java:175)
        at wres.worker.JobStatusMessenger.run(JobStatusMessenger.java:136)
        at wres.worker.WresEvaluationProcessor.executeEvaluation(WresEvaluationProcessor.java:257)
        at wres.worker.WresEvaluationProcessor.call(WresEvaluationProcessor.java:184)
        at wres.worker.Worker.main(Worker.java:137)

```

**Comment by epag** [comment]
So in the embedded server, we kick off the evaluation timeout thread once we START an evaluation. However, as long as a project is IN_PROGRESS we just loop the timeout thread. 

I think the solution is as easy as only kicking off the timeout thread to monitor status transitions. 

So instead of kicking off the timeout thread to monitor we are IN_PROGRESS, we instead kick off the timeout thread when we OPEN the project and it waits a minute to verify that the status has since changed to IN_PROGRESS. 

Then, when the status changes to COMPLETE, we kick of a different timeout thread to make sure we change to CLOSED. 


This will stop us from sleeping in a loop and also remove this race condition

**Comment by epag** [comment]
Putting in the solution now, pretty obscure race condition to hit so no real UAT here
