### ISSUE TITLE
As a developer, I want a better worker-shim logging when a mistake in the INNER_JAVA_OPTS leads to a failure starting the WRES process

### ISSUE THREAD

**Issue by epag** [NOAA-OWP/wres#95]
---

Author Name: **Hank** (Hank)
Original Redmine Issue: 109767, https://vlab.noaa.gov/redmine/issues/109767
Original Date: 2022-11-07

---

Subject says it all.  I've repurposed this ticket to request better logging when the worker-shim attempts to start the underlying WRES process, but something the @INNER_JAVA_OPTS@ is misconfigured so the process fails to start.  See the shared exception in the comments, below, which essentially says nothing useful.

Hank

====== ORIGINAL DESCRIPTION:

While testing #95867, I received this exception:

```
java.lang.InterruptedException: null
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
        at java.base/java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:513)
        at java.base/java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:675)
        at java.base/sun.nio.fs.AbstractWatchService.poll(AbstractWatchService.java:108)
        at wres.worker.JobOutputMessenger.run(JobOutputMessenger.java:119)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

```

Hank

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Hank** (Hank)
Original Date: 2022-11-07T15:05:46Z

---

Code snippet:

```<code class="java">
    @Override
    public void run()
    {
        // To watch files, we have to jump through this hoop: get the filesystem
        FileSystem theFileSystem = FileSystems.getDefault();

        Path innerOutputDirectory = this.getOutputDirectory();

        try ( WatchService outputDirectoryWatchService = theFileSystem.newWatchService() )
        {
            // We assume that the
            this.getOutputDirectory()
                .register( outputDirectoryWatchService,
                           ENTRY_CREATE );

            while ( !this.foundInnerOutputDirectory )
            {
                // Look for the actual inner output directory to be created
                // by the WRES process (inside the one we're watching).
                WatchKey somethingFound =
                        outputDirectoryWatchService.poll( 1, TimeUnit.SECONDS );

                // Then look for files in that inner output directory
                LOGGER.debug( "Found something related to output? {}",
                              somethingFound );
</code>
```

The exception occurs when @outputDirectoryWatchService.poll( 1, TimeUnit.SECONDS )@ is called.  The variable @outputDirectoryWatchService@ must be null.  There is no check against that, but I need to confirm that a null is possible as a result of 

@outputDirectoryWatchService = theFileSystem.newWatchService()@.

Hank

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2022-11-07T15:06:43Z

---

Hank, I doubt this is related to memory settings and is probably yet another ticket. I could be wrong, but I cannot see any connection between the two.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Hank** (Hank)
Original Date: 2022-11-07T15:23:35Z

---

I can't see the relationship either, and yet the NPE doesn't happen if I back out my changes.  

Hank

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Hank** (Hank)
Original Date: 2022-11-07T15:24:35Z

---

Anyway, this it the ticket focused on the NPE, while my experiment with memory settings is in #95867. The two appear to be connected, but I don't understand why/how.

Hank

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2022-11-07T15:31:34Z

---

That isn't an NPE.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Hank** (Hank)
Original Date: 2022-11-07T15:41:09Z

---

I've been misinterpreting the exception.  Its not that the @outputDirectoryWatchService@ is null; its something internal within the call to @poll@.  Note the exception after the reference to @JobOutputMessenger@:

```
java.lang.InterruptedException: null
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
        at java.base/java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:513)
        at java.base/java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:675)
        at java.base/sun.nio.fs.AbstractWatchService.poll(AbstractWatchService.java:108)
        at wres.worker.JobOutputMessenger.run(JobOutputMessenger.java:119)

```

Websearching is getting me no where.  I have even tried to look at the code for @awaitNanos@, for which a different version is available on GitHub, but that got me nowhere.

I'm putting this on-hold and lowering the priority. I have other things to worry about right now.  For future reproduction, go into the entry .yml, add "-Xms=4024m -Xmx=4024m" to the worker @INNER_JAVA_OPTS@ and up the memory limit to 5120m for the worker-shim container.

Thanks,

Hank

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Hank** (Hank)
Original Date: 2022-11-07T15:43:07Z

---

Yeah, I noticed it wasn't an NPE, as well, but something else happening deeper inside the call to "poll".

James wrote:
> In general, I think this file watching is quite brittle and from what I recall interruptions are common and there is documention to that effect in the @JobOutputMessenger@.

Right.  This issue appears to be consistently caused by an increase in the memory via the .yml.  I was going to try to increase the memory through the default settings, but I have other items I need to work on today.  I'll comment on that in #94867.

Thanks,

Hank

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2022-11-07T15:51:26Z

---

Again, I don't think this exception is anything out of the ordinary. Perhaps you haven't seen it before, but I see it routinely when deploying locally. It happens more often than not.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Hank** (Hank)
Original Date: 2022-11-07T16:06:34Z

---

The problem was created because of incorrect syntax in the specification of the memory settings.  I had added, "-Xms=4096m -Xmx=4096m".  Those settings do not use equal signs, '='.  It should have been: "-Xms4096m -Xmx4096m".  

I'm repurposing this ticket to emphasize the need for better logging when underlying WRES process fails to start.  In this case, the above mistake led to this in the worker-shim log:

```
2022-11-07T15:30:22.586+0000 [main] INFO wres.worker.Worker - Waiting for work...
2022-11-07T15:30:22.587+0000 [pool-3-thread-1] WARN wres.worker.JobOutputMessenger - Interrupted while looking for innermost output directory.
java.lang.InterruptedException: null
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
        at java.base/java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:513)
        at java.base/java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:675)
        at java.base/sun.nio.fs.AbstractWatchService.poll(AbstractWatchService.java:108)
        at wres.worker.JobOutputMessenger.run(JobOutputMessenger.java:119)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
2022-11-07T15:30:22.593+0000 [pool-3-thread-1] INFO wres.worker.JobOutputMessenger - Finished sending output messages for job 9037171929809242336

```

You can see the waiting message from before I posted the evaluation, and then the results after I posted the evaluation which just shows that the @JobOutputMessenger@ was unable to observe the output folder for the evaluation; or, rather, it found nothing to observe. Or something like that.

Point is, there is nothing from the process itself in that log message.  Something needs to be there, even if its a basic, "Failed to start the WRES process."

Thanks,

Hank
